### ISSUE TITLE
bug: Weather animations get stuck on transition between 2 maps

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#1725] opened 2023-02-19 16:34 UTC
### Description

You can be walking and the raindrop animations are falling as intended. Then when transitioning between two maps some of the raindrop animations get stuck on the map and stop moving in the direction you set it. This lasts briefly and then vanishes.
Here's a video of what I mean: (https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/a047e4ca9ed40859e835b3394b6aab05.mp4)

### Steps to Reproduce

- Login to said version of the editor 
- add weather 
- make multiple maps
- walk through the many maps with the same weather added to them

### Version with bug

0.7.1.92

### Last version that worked well

unkown

### Affected platforms

Windows

### Did you find any workaround?

No.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment] 2023-11-03 05:10
@Arufonsu Is this fixed by #2005 and #2007 ?

**Comment by Arufonsu** [comment] 2024-07-08 02:35
> @Arufonsu Is this fixed by #2005 and #2007 ?

this is quite late for a reply, but this seems to be fixed with current [v0.8.0-beta.191](https://github.com/AscensionGameDev/Intersect-Engine/releases/tag/v0.8.0-beta.191) (I'm unable to reproduce this)

**Closed by Arufonsu** 2024-07-08 02:35 UTC
Labels: bug, needs verification
