### ISSUE TITLE
Add "Stat Bonus Range % +/-" as an option to Item Editor

### ISSUE THREAD

**Issue by WehrJ** [AscensionGameDev/Intersect-Engine#1039] opened 2022-01-05 22:25 UTC
I would like to have equipment be able to roll a range of stats without adding stats that are set to 0, and more tightly control how the range impacts the overall stats provided.  By adding a Stat Bonus range **%** option, you could ensure the "primary" stat on an item gets  an appropriate range without potentially inflating the overall stat pool of players by static increases from 0 on other stats.

**Comment by AlexVild** [comment] 2022-01-10 03:23
I added a feature to my fork that was a checkbox that locked stats. It looks like this:
![image](https://user-images.githubusercontent.com/8580915/148714849-1cc41cd9-0062-4155-9814-440b31473127.png)

Basically, if something has a "locked" stat, then it won't budge when we're calculating stats that are "unlocked", when calculating stats based off the "Stat Bonus Range" set by a dev.

Is this what you'd want? And also, would others find this useful enough to get this in?

**Comment by WeylonSantana** [comment] 2022-09-06 17:20
Duplicate of #200

**Closed by WeylonSantana** 2022-09-06 17:20 UTC
Labels: feature request
