### ISSUE TITLE
Bag does'nt work after a reconnect

### ISSUE THREAD

**Issue by lucas-tardivo** [AscensionGameDev/Intersect-Engine#600] opened 2021-03-15 17:41 UTC
**Describe the bug**
The bags can opened but any interaction does not work after a reconnect, Basically the HasBag function cannot find the respective bag because the Bag attribute is being loaded as null, so the function returns any interaction.

**Version Encountered**
v0.7.0.0

**To Reproduce**
1. Get a bag item
2. Open it
3. See it works well
4. Close the client and log again
5. Open the bag, any interaction does not work

**Expected behavior**
The interactions works well after reconnect

**Operating System:**
Windows

**Comment by Arufonsu** [comment] 2021-03-17 21:17
>     5. Open the bag, any interaction does not work
> 
> 
> **Expected behavior**
> The interactions works well after reconnect

I couldn't reproduce this. besides, it seems like by default you can't walk nor interact with anything while a bag its open.
You can walk and interact around if you close the bag, reconnecting isn't necessary.

**Comment by lucas-tardivo** [comment] 2021-03-17 21:47
Sorry for did'nt specify well @Arufonsu , the interactions i mean is to put/get items on the respective bag

**Comment by Magehernan** [comment] 2021-03-22 20:50
hi, i found a bug with this, i don't know if is like you describe about after reconnect, to me happens always, i already have the bag in the player inventory.

I debug it and i found that when checking comparing to check if the player HasBag

https://github.com/AscensionGameDev/Intersect-Engine/blob/9ac502785d1584917ab584ddb365d4f87727458e/Intersect.Server/Entities/Player.cs#L3164-L3175

the bag inside the items is null because when you open the bag... 

https://github.com/AscensionGameDev/Intersect-Engine/blob/9ac502785d1584917ab584ddb365d4f87727458e/Intersect.Server/Entities/Player.cs#L3131-L3163

In the line 3154 it assign the new bag to the item only if the bag is new... so because this the bag in the item is null.

I look back and found this commit 1a8edc5 - fix 191: Bag access is done via cached value (#219)
and in here the code is this
```csharp
 //Bag
        public bool OpenBag(Item bagItem, ItemBase itemBase)
        {
            if (IsBusy())
            {
                return false;
            }

            //Bags will never, ever, be stackable. Going to use the value property for the bag id in the Database.
            if (bagItem.Bag == null)
            {
                bagItem.Bag = DbInterface.GetBag(bagItem);
                if (bagItem.Bag == null) //Bag doesnt exist, create it!
                {
                    //Create the Bag
                    var slotCount = itemBase.SlotCount;
                    if (slotCount < 1)
                    {
                        slotCount = 1;
                    }

                    bagItem.Bag = new Bag(slotCount);
                }

                bagItem.Bag.Slots = bagItem.Bag.Slots.OrderBy(p => p.Slot).ToList();

                foreach (var itm in bagItem.Bag.Slots)
                {
                    if (itm.ItemId != Guid.Empty && ItemBase.Get(itm.ItemId) == null)
                    {
                        itm.Set(new Item());
                    }
                }
            }

            //Send the bag to the player (this will make it appear on screen)
            InBag = bagItem.Bag;
            PacketSender.SendOpenBag(this, bagItem.Bag.SlotCount, bagItem.Bag);

            return true;
````

now is checking for the bagItem.Bag and if is null it go to the database and get it and assiging it to the item, because this it assign the value and works but with the change only if it is a new bag it get assigned.
So i fix it moving the line 1354 outside the if  at 1356 and it fix the problem.

I hope it helps

**Comment by lucas-tardivo** [comment] 2021-03-23 15:31
@Magehernan thanks man! You helped me to figure out the problem.

- The **first problem** is that the engine is not setting the Item BagId property when a new bag is created. So saved the bag right after create it to make a database new Guid and then set it to the item.
- The **second problem** is that the Item Bag property is not being setted after the bag is loaded/created, this makes the "HasBag" function always return false, which forbidden any item to be put or get. To resolve that, i added a bagItem.Bag = bag after the TryGetBag if.

This is not the best solution cause im sure that you guys got a better fix for that, but it works for me atm hahahah
Im copying this to @Arufonsu @jcsnider so a fix can be done for a future revision. If you guys wants me to open a Pull Request, just leave a comment describing how you would do the correct solution and then i try it on code :P
Tnx again!

**Comment by blinkuz** [comment] 2021-03-23 20:24
@lucas-tardivo I think that although the solution is not the best because the fact of making it work in a basic way is already progress, I would say that try to send a PR with the changes that you have made since as I said before, making it work is better than having it bug like is right now.

**Comment by Magehernan** [comment] 2021-03-23 21:18
Hi, i look more in deep the code and i think the problem is in this function.

https://github.com/AscensionGameDev/Intersect-Engine/blob/9ac502785d1584917ab584ddb365d4f87727458e/Intersect.Server/Database/Item.cs#L122-L139

When property Bag is null it try to load from the Database and then it isn't assign to the property Bag so it isn't really loaded and it returns true.

I assign the bag loaded to the property Bag and for me it works good, if there is another problem when it is created i don't know but i think there are differents problems.

I will fork the repo and submit a pull request.

**Comment by lucas-tardivo** [comment] 2021-03-24 12:56
@blinkuz You're right, i'll fork the repositry and send a PR :)
@Magehernan i think it fixed one of the problems but the item still don't saving the BagID, so it wont work after a reconnect. I'll make a PR to fix that one

**Comment by Magehernan** [comment] 2021-03-24 13:17
@lucas-tardivo i only have the problem that the bags do nothing when try to store or retrive items, i don't have problems when reconnecting, i can close and reopen the game and it work fine, i am working from prerelease branch.

**Comment by lucas-tardivo** [comment] 2021-03-24 13:24
@Magehernan Actually you're right. The second problem was a consequence from the first one. My inventory did'nt save the BagIDs so it keeps my account inventory with bugs hahah. 
The problem is fixed, thanks you guys :)

**Comment by jcsnider** [comment] 2021-04-18 12:22
Thanks for the fix @Magehernan , please let me know if you all encounter other bag issues!

**Closed by jcsnider** 2021-04-18 12:22 UTC
Labels: bug
