### ISSUE TITLE
Unknown server error resulted in premature abort of console thread

### ISSUE THREAD

**Issue by ThousandX** [AscensionGameDev/Intersect-Engine#80] opened 2020-04-04 18:16 UTC
**Describe the bug**
I left the server on, it must have crashed during the night, I went to check the error logs, and I had this

**Version Encountered**

**To Reproduce**
Just leave the server open.

**Logs**
```
2020-04-03 22:18:44.815 [Error] 
  Message: Thread was being aborted.
    Stack:    at System.IO.__ConsoleStream.WaitForAvailableConsoleInput(SafeFileHandle file, Boolean isPipe)
   at System.IO.__ConsoleStream.ReadFileNative(SafeFileHandle hFile, Byte[] bytes, Int32 offset, Int32 count, Boolean useFileAPIs, Boolean isPipe, Int32& bytesRead)
   at System.IO.__ConsoleStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.IO.TextReader.SyncTextReader.ReadLine()
   at System.Console.ReadLine()
   at Intersect.Console.ReadLine() in G:\Celtos Online\Intersect-Engine\Intersect (Core)\Console.cs:line 362
   at Intersect.Server.Core.ServerConsole.ThreadStart()
```

**Operating System:**
Windows Server 2016

[error.txt](https://github.com/AscensionGameDev/Intersect-Engine/files/4432198/error.txt)

**Comment by lodicolo** [comment] 2020-04-04 19:31
PR #81 does not resolve this issue, but this issue is not caused by the exception that was logged. New logs (both error and regular logs) are needed after #81 is merged.

**Closed** 2020-04-07 21:22 UTC
Labels: blocked, bug
