### ISSUE TITLE
bug: MySQL alter db error

### ISSUE THREAD

**Issue by zertex** [AscensionGameDev/Intersect-Engine#2187] opened 2024-03-23 12:06 UTC
### Description

[Error] 20102 - Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `UserActivityHistory` MODIFY COLUMN `UserId` TEXT CHARACTER SET utf8mb4 NOT NULL;
2024-03-23 12:01:03.053 [Error] Received unhandled exception from System.Threading.Thread: Table 'game2d.UserActivityHistory' doesn't exist

### Steps to Reproduce

1. On Centos7: ./server

### Version with bug

0.8.0.137

### Last version that worked well

0.8.0.137

### Affected platforms

Linux

### Relevant log output

```shell
No migrations pending, skipping...
2024-03-23 12:01:03.049 [Error] 20102 - Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `UserActivityHistory` MODIFY COLUMN `UserId` TEXT CHARACTER SET utf8mb4 NOT NULL;
2024-03-23 12:01:03.053 [Error] Received unhandled exception from System.Threading.Thread: Table 'game2d.UserActivityHistory' doesn't exist
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2024-03-23 14:18
1) Steps to reproduce? closing this as invalid for now, update the issue with proper steps to reproduce... and make sure you are using an unmodified project
2) Seems like you are using a customized engine? `game2d.UserActivityHistory` doesn't seems to be anywhere in the code? that should actually point over to `Logging.UserActivityHistory` - we do not provide support to modified projects, (seems like you changed the original solution names and databases to make it seems like is not actually intersect? i could be wrong but i'm assuming that by judging your logs ... )

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/d118c253-c12f-4c0b-8878-d1493caddaf6)


![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/08e818c2-71c2-43ce-993d-803c9172f6d4)

**Closed by Arufonsu** 2024-03-23 14:18 UTC
Labels: invalid, not an issue

**Comment by zertex** [comment] 2024-03-23 15:32
What is this?

[Intersect.Server/Migrations/MySql/Logging/20201119230003_AddUserActivityHistory.cs](https://github.com/AscensionGameDev/Intersect-Engine/blob/e8535fbc7b0bbf53364f0dd8c12231a46ac42e6c/Intersect.Server/Migrations/MySql/Logging/20201119230003_AddUserActivityHistory.cs#L5)



> 1. Steps to reproduce? closing this as invalid for now, update the issue with proper steps to reproduce... and make sure you are using an unmodified project
> 
>     2. Seems like you are using a customized engine? `game2d.UserActivityHistory` doesn't seems to be anywhere in the code? that should actually point over to `Logging.UserActivityHistory` - we do not provide support to modified projects, (seems like you changed the original solution names and databases to make it seems like is not actually intersect? i could be wrong but i'm assuming that by judging your logs ... )
> 
> 
> ![image](https://private-user-images.githubusercontent.com/17498701/316246903-d118c253-c12f-4c0b-8878-d1493caddaf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDgyMDcsIm5iZiI6MTcxMTIwNzkwNywicGF0aCI6Ii8xNzQ5ODcwMS8zMTYyNDY5MDMtZDExOGMyNTMtYzEyZi00YzBiLTg4NzgtZDE0OTNjYWRkYWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE1MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MWI2NmU4NTFlYzliYWE1Mjg4MGQ4NGFkNjM5NzNlMjdiZTk5ZWEzZmZlMGE5NjA3NjM1ZTk0N2VhYzEyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7XtKpGt6U67eO4EWcQcLthr_v_0VZY2YDLnKd1qVYPk)
> 
> ![image](https://private-user-images.githubusercontent.com/17498701/316246890-08e818c2-71c2-43ce-993d-803c9172f6d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDgyMDcsIm5iZiI6MTcxMTIwNzkwNywicGF0aCI6Ii8xNzQ5ODcwMS8zMTYyNDY4OTAtMDhlODE4YzItNzFjMi00M2NlLTk5M2QtODAzYzkxNzJmNmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDE1MzE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMTFkNWVmMjY2NmM4ZTRjNTBkMjc0OWY4ZmY1MWU3ZDdhYmQ1ZTEyYjdkMjE4MmI5NzkyZGIzNzYwOTBiOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OqjnA-VHJm9ZndhtLIhHZuy9ZF8soQ3DZFr7jRLSCRs)
