### ISSUE TITLE
bug: "Craft All" doesn't work correctly if there is mild latency between client/server

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1350] opened 2022-06-29 15:25 UTC
### Description

On a connection with >40ms or so ping, "Craft All" might not work all the time.

This is because "Craft All" is a client-sided action and doesn't actually officially know _when_ its last crafting attempt was completed.

The server, when crafting an item in `Player#CraftItem()`, calls `TryGiveItem()` when it's done trying to craft. When that call sends an `InventoryUpdatePacket` to the client, the client then proceeds to attempt to craft the next item. This causes the server to set the players `CraftId` property to whatever the "Craft All" request desires.

HOWEVER, if there is some latency, the server has yet to hit a line in `Player#CraftItem()` that sets the CraftId to empty:

`CraftId = Guid.Empty`

What's happening on latent servers is that the line above gets hit _after_ the most recent "CraftItemPacket" has been sent to the server - so, when the server finishes crafting the latest item, it's actually... no item, and the "Craft All" ceases.

### Steps to Reproduce

Quite tricky to reproduce - I would recommend hosting the server on a remote machine somewhere far from your location.

1. Craft All on some item
2. See that the subsequent craft attempt fails.

### Version with bug

7.x

### Last version that worked well

Unknown, likely none since Craft All introduced

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Yes.

By moving the `CraftId = Guid.Empty` from the last thing that happens in `Intersect.Server/Player#CraftItem()` to the _first thing that happens after successfully giving the player their crafted item_, it reduces the severity of the bug. I have reason to believe this does not _solve_ the problem, but makes it so that you would need much more lag/a much slower server for this to be the case.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2022-07-03 21:39
The issue/topic *should be* a dupe of #1219 (due to date of creation ; despite that, this one is more detailed and has a proposed workaround), since you are both collaborators, try to decide what's up with the bug/topic (which one to label as dupe and where the topic shall continue for a PR to fix it up), as for what it involves, i can confirm and verify that this is actually an issue happening as described.

**Comment by WeylonSantana** [comment] 2022-07-03 22:21
I'm willing to close mine without any problems, but it's worth mentioning here, that in my report, I specify that the bug also happens offline, (which doesn't involve latency), so it should be checked if this workaround also works for the offline version.

**Closed** 2022-09-25 22:06 UTC
Labels: bug, verified
