### ISSUE TITLE
bug: menu background not working

### ISSUE THREAD

**Issue by froggytrav** [AscensionGameDev/Intersect-Engine#1252] opened 2022-05-09 10:10 UTC
**Describe the bug**
The menu when launching the client shows a black image. When i open the config and change the background to the correct image and save, it simply resets to [ ] when i reload the config

**Version Encountered**
0.7.1.14

**To Reproduce**
1. Go to client config
2. set background to whatever image and save
3. load client

**Expected behavior**
should load the correct background image

**Comment by Arufonsu** [comment] 2022-05-09 18:06
Closing this: tried to reproduce with no success, both, static and animated background are working without an issue.

Next time: try to be more specific when explaining how to reproduce this issue, i'm going to go ahead and assume that you didn't properly formatted the index list for the background sprite since you are probably not aware of the recent changes.

[Check out this video from the PR that implemented the latest changes around this feature](https://github.com/AscensionGameDev/Intersect-Engine/pull/1044#issuecomment-1013455445)

**Closed by Arufonsu** 2022-05-09 18:06 UTC
Labels: bug
