### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#266] opened 2020-07-01 21:35 UTC
**Describe the bug**
Often the client simply closes. On another computer it also presented the same thing. It just closes. There is no regularity, sometimes it closes in 30 min, sometimes after 2 hours. Sometimes it doesn't even close.

**Version Encountered**
0.6.2.241 (current)

**Logs**
[Intersect Client-2020_06_29-09_46_24_653.log](https://github.com/AscensionGameDev/Intersect-Engine/files/4860682/Intersect.Client-2020_06_29-09_46_24_653.log)
[errors-Intersect Client.log](https://github.com/AscensionGameDev/Intersect-Engine/files/4860685/errors-Intersect.Client.log)

**Operating System:**
Windows

**Comment by lodicolo** [comment] 2020-08-24 02:24
This is a crash that is occurring in Monogame ([here](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Audio/DynamicSoundEffectInstance.OpenAL.cs#L137)), and not one that we can fix within Intersect.

Realistically this should not happen, but from a quick glance at the source code I would guess that the buffer queue and OpenAL are getting desynced somehow, and there is no steps to ensure the dequeue call is safe.

If someone who can reproduce this wants to dive deeper into this please do so, but ultimately a bug needs to be opened against Monogame with a fuller understanding of the cause (otherwise any fix may just be masking a bigger problem).

Because this isn't our crash and there are not enough details to proceed with an investigation, I'm closing this until we have information pinning this on Intersect's usage of Monogame.

This could also be related to specific audio files, so you might be able to figure out if only some reproduce it.

**Closed by lodicolo** 2020-08-24 02:24 UTC
Labels: bug
