### ISSUE TITLE
bug: transformed player sprite animation gets stuck

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1717] opened 2023-01-29 19:51 UTC
### Description

Often after a Player uses a Transform Spell - the Transformed sprite does not play any animations. (this seems to be triggered  randomly and gets stuck that way) The spite appears static.

Hard to catch what exactly is causing this, but seems to only happen when in a party:
https://youtu.be/WTARcc0xaEI
(Go to 12:15 in the video to see the bug happen)

<s>This seems it may be in relation to the recent Transform Bug fix:  _transformed casting sprite behavior (#1673)_</s>

### Steps to Reproduce

1. Create a transform spell
2. Use spell to Transform to new sprite
3. Randomly get stuck in static position

### Version with bug

v0.7.1.88

### Last version that worked well

not sure

### Affected platforms

Windows, macOS

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2023-02-02 17:39
Edited the issue title and description. FYI #1673 is not related to this issue, that PR fixed a behavior that wasn't properly implemented which had no relation on how the sprite frame animations are handled (problem seen in this report) but instead, to which sprite was used while transformed instead.

If you are up to dev testing, [could you give this PR](https://github.com/AscensionGameDev/Intersect-Engine/pull/1674) a go and see if it fixes the reported bug?

**Comment by Arufonsu** [comment] 2023-02-12 19:49
Hello again, are you able to dev and compile your own solutions? take a look over the protected override void DrawEquipment at Intersect.Client/Entities/Player.cs

https://github.com/AscensionGameDev/Intersect-Engine/blob/387d22f7c3b0aab8c4cca5907f174c1db33f38a4/Intersect.Client/Entities/Player.cs#L2144


And change the method like the following:
![imagen](https://user-images.githubusercontent.com/17498701/218333540-aa48d8b4-37ca-4c2f-9468-3a2cbc1281bc.png)


I won't be around my desktop for a while, if you wish, feel free to test this and let us know if it fixes the reported issues.

**Comment by Arufonsu** [comment] 2023-09-10 15:06
Closing this since no answer has been given since Feb 2nd, 2023 ; 
Please let us know if this issue persists and if you manage to reproduce this again so we can tackle this down along

**Closed by Arufonsu** 2023-09-10 15:06 UTC
Labels: bug, help wanted, cannot be reproduced, needs verification
