### ISSUE TITLE
feature: option to read more than one type of client_strings.json

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1148] opened 2022-03-24 19:18 UTC
**Is your feature request related to a problem? Please describe.**
It would be really cool if the player could change the translation file, so that at least the game interface becomes language compliant

**Describe the solution you'd like**
For example, in the settings menu, a combox, which will show all clients_string_*.json that are inside the RESOURCES folder.
for example:
client_strings_en.json = it will add the English language.
client_strings_es.json = it will add Spanish language.
And so on, as it will pull an automatic language name.

inside client_string_(of the chosen language).json
will have a
Language_name = English;

The client will automatically know how to name it when it pulls in the Combox

**Comment by Arufonsu** [comment] 2022-03-25 03:13
Although it is requested differently, the idea is basically the same and has been requested before: 
add a combobox to select the language within the game settings (taking into account how the categories are structured now).

closing as a duplicate of #599

**Closed by Arufonsu** 2022-03-25 03:13 UTC
Labels: duplicate, feature request
