### ISSUE TITLE
Buff & Debuff Effects Cannot Be Cleansed

### ISSUE THREAD

**Issue by jessidion** [AscensionGameDev/Intersect-Engine#1093] opened 2022-03-02 06:37 UTC
**Describe the bug**
You can cleanse an effect, but if that effect had stats buffs/debuffs, those effects will remain.

**Version Encountered**

0.7.0.129

**To Reproduce**
1. Make a stat buff/debuff spell
2. Make a cleanse spell
3. Use the stat buff/debuff spell
4. Use the cleanse spell
5. See issue

**Expected behavior**
The stats buffs/debuffs should be removed as well.

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 10

**Additional context**

**Comment by Arufonsu** [comment] 2022-03-02 14:53
Duplicate of #457 
Closing this.

**Closed by Arufonsu** 2022-03-02 14:53 UTC
Labels: duplicate
