### ISSUE TITLE
Issue w/ friend list & removing friends 

### ISSUE THREAD

**Issue by Guite-Emortal** [AscensionGameDev/Intersect-Engine#241] opened 2020-05-29 04:59 UTC
**Describe the bug**
When you move your mouse over a users name in the friends list the audio spams, sounds almost like static. To remove friends you have to move your mouse back and forth while spamming the right click.

**Version Encountered**

0.6.2.420

**To Reproduce**
1. Add someone to friendslist
2. Move mouse over their name
3. Attempt to right click to remove

**Operating System:**
Windows

**Comment by Azurebeats** [comment] 2020-05-31 14:24
So far, in my testing it seems that Gwen definitely realises that you are hovering over the right element.. But upon clicking it the item you're clicking is somehow Null.

I've noticed that it's not a listbox problem itself though, as it would appear that the ListBox used for chat works at all times and always returns that you're clicking the row itself.

Can't quite figure out where this is coming from though, possibly because the Listbox is in a WindowControl?

**Comment by lodicolo** [comment] 2020-08-24 04:13
I think this is shares the same root cause as #174 

Assigning to JC

**Closed** 2020-09-27 10:47 UTC
Labels: bug
