### ISSUE TITLE
bug: Projectiles don't "attack" resources if resource tool is set to none

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#2168] opened 2024-02-17 14:26 UTC
### Description

Not sure if this is a bug or intentional. When a resource on a maps tool is set to none a player can walk up and attack the resource with no weapon or a mele weapon equipped. This makes since for things like barrels and destructible environment pieces. But if a player has a weapon with a projectile equipped the projectile does not damage the resource it just stops and disappears. To me it would make sense that all projectiles would damage the resource just like a mele weapon. 

### Steps to Reproduce

create a resource and set the tool to "none"
create a weapon with a projectile
try to shoot the projectile at the resource

### Version with bug

0.8.0.132

### Last version that worked well

never

### Affected platforms

Windows

### Did you find any workaround?

no

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment] 2024-06-07 13:50
seems to be intentional in code

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/2901641b-7f6c-4dab-abae-493bb8bbd8ea)

You can only attack resources if the projectile has a spell attached to it, apparently?
@Arufonsu thoughts here, whether we should close or not

**Comment by Arufonsu** [comment] 2024-06-08 17:26
> seems to be intentional in code
> 
> ![image](https://private-user-images.githubusercontent.com/63019821/337675783-2901641b-7f6c-4dab-abae-493bb8bbd8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4Njc0OTQsIm5iZiI6MTcxNzg2NzE5NCwicGF0aCI6Ii82MzAxOTgyMS8zMzc2NzU3ODMtMjkwMTY0MWItN2Y2Yy00ZGFiLWFiYWUtNDkzYmI4YmJkOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDE3MTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWEwNmM5OGYxZmE2NjFkNjFkOWVhODM1ZDQ1NTJiNmYxNjU5YjUyMmJmMjk5ODlhYTFiNzQzYzg3ZjA1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2EexckFFDgKnAPjO5VHAgu3VHMhmXR9lztYaJRzOIS0)
> 
> You can only attack resources if the projectile has a spell attached to it, apparently? @Arufonsu thoughts here, whether we should close or not

pretty sure this was intentional due to some issues that normal attacking projectiles had with resources, i would see this as a valid enhancement since we in fact already have the ability to destroy resources on melee weapons and while unarmed, makes me wonder for sure why projectiles couldn't damage resources.

if OP is still interested on this, i would honestly start this as an enhancement proposal for projectiles, even if is not OP's expected behavior, is not really a bug breaking anything in the game itself

**Comment by Arufonsu** [comment] 2024-06-08 17:35
Reference:

https://github.com/AscensionGameDev/Intersect-Engine/commit/50cd3536e69455ea9d8988441109a86690e64ab1#diff-983a1f43ad6b92f3105611e755b56c9d8b9a343dacb206995f0b0589749a3856R679

**Comment by Arufonsu** [comment] 2024-07-07 23:49
> @Arufonsu thoughts here, whether we should close or not

i'll close this for now, [considering the code history, this was intentional,](https://github.com/AscensionGameDev/Intersect-Engine/issues/2168#issuecomment-2156115000) thus, this should be an enhancement/discussion request.

**Closed by Arufonsu** 2024-07-07 23:49 UTC
Labels: bug, verified
