### ISSUE TITLE
bug: Packet Deserializing Failure

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#2270] opened 2024-06-09 00:26 UTC
### Description

The server notifies users of packets that were unsuccessful in being deserialized

### Steps to Reproduce

unknown so far

### Version with bug

current

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Relevant log output

Server Status
```shell
2024-06-09 00:06:39.320 [Error] MessagePackSerializationException: Failed to deserialize Intersect.Network.Packets.Unconnected.Server.ServerStatusResponsePacket value.
    Stack:    at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at lambda_method2377(Closure, ReadOnlyMemory1, MessagePackSerializerOptions, CancellationToken)
   at MessagePack.MessagePackSerializer.Deserialize(Type type, ReadOnlyMemory1 bytes, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at Intersect.Network.MessagePacker.Deserialize(Byte[] packetData, Boolean silent) in C:\Users\ZACKY\Documents\GitHub\Intersect-Engine\Intersect (Core)\Network\MessagePacker.cs:line 37

Caused By
MessagePackSerializationException: Unexpected msgpack code 197 (bin 16) encountered.
    Stack:    at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.ReadInt32()
   at MessagePack.Formatters.GenericEnumFormatter1.<>c.<.ctor>b__4_5(MessagePackReader& reader)
   at MessagePack.Formatters.GenericEnumFormatter1.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.Formatters.Intersect_Network_Packets_Unconnected_Server_ServerStatusResponsePacketFormatter2.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
```

Trade Packet

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/4fcfdca5-f413-43e6-a3f8-9fcbabf11344)

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2024-06-09 00:27
is this happening on unmodified intersect projects? please make sure that these logs aren't from custom sources

**Comment by WeylonSantana** [comment] 2024-06-09 00:29
> is this happening on unmodified intersect projects? please make sure that these logs aren't from custom sources

the first log is from xZACKYx from 167 version
second log is from custom source i've modified
but the logs are the same, which proves that the source is in the base and not in the modifications made

**Comment by Arufonsu** [comment] 2024-06-14 03:27
has this been confirmed with steps to reproduce by OP yet (?)

**Comment by Arufonsu** [comment] 2024-06-16 15:21
closing this, been unable to reproduce this issue and OP stated on discord that they no longer have this issue and it was related to their custom changes.

**Closed by Arufonsu** 2024-06-16 15:21 UTC
Labels: bug, needs verification
