### ISSUE TITLE
Server crashes, but on the console everything is fine

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#101] opened 2020-04-06 17:48 UTC
**Describe the bug**
This problem is happening directly, I can't leave the server on for 24 hours, because it can't stay, I get messages from players asking if the server is under maintenance, but when I check everything is ok on the console

**Version Encountered**
Version 0.6.2.0 (LASTEST PULL DEV)

**To Reproduce**
Just leaving the server on, one hour it stopped working

**Expected behavior**
Let it not fall, or at least make an error

**Screenshots**
![Screenshot_8](https://user-images.githubusercontent.com/21990960/78588844-b08e8d00-7815-11ea-833f-10a176504276.png)
![Screenshot_9](https://user-images.githubusercontent.com/21990960/78588846-b1bfba00-7815-11ea-8690-29a824185075.png)

**Logs**

> 2020-04-06 07:39:26.468 [Error] 
  Message: Thread was being aborted.
    Stack:    at System.IO.__ConsoleStream.WaitForAvailableConsoleInput(SafeFileHandle file, Boolean isPipe)
   at System.IO.__ConsoleStream.ReadFileNative(SafeFileHandle hFile, Byte[] bytes, Int32 offset, Int32 count, Boolean useFileAPIs, Boolean isPipe, Int32& bytesRead)
   at System.IO.__ConsoleStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.IO.TextReader.SyncTextReader.ReadLine()
   at System.Console.ReadLine()
   at Intersect.Console.ReadLine() in G:\Celtos Online\Intersect-Engine\Intersect (Core)\Console.cs:line 362
   at Intersect.Server.Core.ServerConsole.ThreadStart()

**Operating System:**
Windows Server 2016

**Comment by lodicolo** [comment] 2020-04-06 20:06
Duplicate of #80

**Closed by lodicolo** 2020-04-06 20:06 UTC
Labels: bug, duplicate
