### ISSUE TITLE
feature: in-game settings for multi-language selection

### ISSUE THREAD

**Issue by theceltos** [AscensionGameDev/Intersect-Engine#599] opened 2021-03-13 11:45 UTC
**Is your feature request related to a problem? Please describe.**
It would be interesting for any project, the player to be able to choose the language of the game interface.

**Describe the solution you'd like**
An option in the configuration menu, a listbox, which will read all language files inside a folder "/resources/lang/en.json" for example

**Comment by Cheshire92** [comment] 2021-03-16 20:15
I think this is a slightly bigger feature than loading in just the client file since the server (and database) both have localisation files as well. I do believe it's something that's in the future to-do list however.

**Comment by dhmhc** [comment] 2021-03-16 21:29
I imagine it could be that way.
For example, let's imagine that you have 2 language files inside the server and on the client, language_en.json and language_es.son (English and Spanish)
The moment the player selects the language en in the client, the server will send language packs referring to language_en.json.

Now for description of the items, monsters, I've been thinking about something like, what if it was possible for the server to auto-translate from English -> to the language configured on the client? Like a google translator, I know that the translations are not the best, but if possible, would it be good?

**Comment by Arufonsu** [comment] 2021-03-17 21:36
Language select should be a thing, sounds nice and makes it so we can have a single and dynamic game client. **But** each language shouldn't be linked to a single central server where players from all around the world will overload our precious digitalized service. Each language should be linked to a specific server depending on the geographic location of the ones who wish to play the game on their local native language. Ofc its always up to the game distributors if they may invest or not in a "global" kind of server (usually localized in english, since its the second most spoken language by bi-linguals in the world), but usually, it happens a lot that mmos have their specific localized strings on separated servers across the globe, in order to prevent legal issues, latency issues, among with many other issues (like language barriers among the community of players within the server.)

**Ex.** Playing a game hosted in japan its laggy as hell to me (350ms+ by considering my current geographic location), and i don't understand japanese (well i do, sort of, but not natively speaking), then i choose to play in the closest server to avoid lag and language barriers.

**Comment by lodicolo** [comment] 2023-11-03 06:34
Dupe of #453

**Closed by lodicolo** 2023-11-03 06:34 UTC
Labels: feature request
