### ISSUE TITLE
enhancement: new spells effects and stats

### ISSUE THREAD

**Issue by iceicebabyy** [AscensionGameDev/Intersect-Engine#2293] opened 2024-06-26 15:17 UTC
### Description

I would like to suggest adding to the effects not only the improvement or deterioration of physical attack, magical attack, physical defense, magical defense, and movement speed. But also to include the improvement or deterioration of cooldown, attack speed, evasion probabilities, increase/decrease of HP/MANA, increase/decrease of HP/Mana regeneration, and the possibility of reviving oneself or the target. 

Additionally, lastly, the possibility that the dash can cause damage upon impacting a target.

### Intended Use-Case

This will help users of the engine to be more creative and expand their possibilities in adding effects to each of the spells.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment] 2024-06-26 15:54
closing as duplicate of #1870
If we had everything in one editor then it would be better to handle and customize, in addition to the effects you mentioned, so it's duplicate

**Closed by WeylonSantana** 2024-06-26 15:54 UTC
Labels: enhancement
