### ISSUE TITLE
enhancement: On Death Animation

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#1460] opened 2022-09-23 00:47 UTC
### Description

I think an "on death" animation for any sprite entity should be a standard out-of-the-box feature. Its great we have animation sprite sheets for attack, idle casting ect. The one main one missing that is usually standard for modern games is the on-death animation.

### Intended Use-Case

Display an animation of the player or enemy falling over to the ground when killed.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment] 2022-09-24 10:36
Before checking the checkbox "This /feature/bug/enhancement idea is not a duplicate to the best of my knowledge.", we ask that you really verify that it is not a duplicate, or if the feature/enhancement has not already been partially created so you can add more information.

Searching for keywords, could have found (if any)
![image](https://user-images.githubusercontent.com/63019821/192093326-2df9cf79-1150-4304-b094-b70b14284141.png)

I'm closing it as a duplicate of #400, but adding the information you'd like for players as well.

**Closed by WeylonSantana** 2022-09-24 10:36 UTC
Labels: enhancement
