### ISSUE TITLE
Buff active doesn't display

### ISSUE THREAD

**Issue by Kamusvalenzuela** [AscensionGameDev/Intersect-Engine#550] opened 2021-02-16 19:37 UTC
**Describe the bug**
When you use a buff or something like that (Shields, increase ad/ap/etc.) the active effect on the players doesn't show

**Version Encountered**

0.7.0.106
**To Reproduce**
1. Make a buff spell
2. Learn it and use on you or other player
3. See the error

**Expected behavior**
On olders versions of Intersect when you use a buff or shield the buff was displayed correctly, and now not
that its the expected work

**Screenshots**
![bug](https://user-images.githubusercontent.com/51339474/108112648-28078c80-7075-11eb-8477-f414620c7050.png)
![bug2](https://user-images.githubusercontent.com/51339474/108112651-2938b980-7075-11eb-9186-fdeaae889e35.png)

**Operating System:**
All

**Comment by jcsnider** [comment] 2021-02-16 19:41
Dupe of #520

**Closed by jcsnider** 2021-02-16 19:41 UTC
Labels: bug, duplicate
