### ISSUE TITLE
(duplicated) parallel quest objectives/tasks

### ISSUE THREAD

**Issue by froggytrav** [AscensionGameDev/Intersect-Engine#1253] opened 2022-05-09 10:37 UTC
**Is your feature request related to a problem? Please describe.**
I am always frustrated when designing quests and you have to create one quest per NPC to kill, or item to gat her.
For example, say I am designing and a dungeon, and there will be quests to eliminate the monsters of said dungeon. Instead of having to create the same amount of quests as there are types of monsters in the dungeon, you should be able to allow players to complete specific tasks in any order

**Describe the solution you'd like**
What I want to happen is a (the way to go about it is up to the devs i think?) a setting where you can group up certain tasks (regardless of kill/gather), so it would look something like this:
Quest starts
NPC tasks player with eliminating 2 types of monsters, A & B.
--Task 1: Eliminate 8 Monster A
--Task 2: Eliminate 8 Monster B
--Task 3: Gather 6 Shoes
Task 1, 2 & 3 completed --> return to NPC

So the solution here would be to somehow group up task 1, 2 & 3 so they can be completed and worked on in any order. The current workaround is to create a quests for each task.

**Additional context**
Context to this is that this is a pretty much basic MMO/RPG feature in just about any game. It would save space and reduce clutter when creating quests/tasks etc

**Comment by Arufonsu** [comment] 2022-05-10 00:46
Closing this since it's a dupe of #1051moved this entire issue report there, since i previously asked you to properly format #1051 (and you didn't..) please avoid opening reports on existing topics/issues/requests, ideally in this case you should have edited the original topic instead of opening a new report.

**Closed by Arufonsu** 2022-05-10 00:46 UTC
Labels: duplicate

**Comment by froggytrav** [comment] 2022-05-10 07:11
What do you mean properly format??? I followed the format that's there when you open a new issue! And i opened a new One since you just closed the last one i opened a year ago for the same reason whats your problem????? What more do you want except that i answer the questions?

**Comment by froggytrav** [comment] 2022-05-10 14:48
Actually you know what, fuck it i dont i dont care, do whatever

Den tis 10 maj 2022 16:25Arufonsu ***@***.***> skrev:
