### ISSUE TITLE
bug: Backpack ignoring stack limit

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1242] opened 2022-04-30 01:14 UTC
**Describe the bug**
When I put 4 stacks of 100 potions in a backpack, they stack up, leaving 400 in the backpack, and when I take back the items from the backpack, they go back to the inventory as 400, not 4 packs of 100

**Version Encountered**
0.7.1.9

**To Reproduce**
1. Have 4 packs of 100 potions of the same type in your inventory, and have 1 backpack as well
2. Put the potions in the backpack, and watch them build up completely ignoring the 100 stack, as configured in the editor.
3. Take the items back from the backpack, they don't come back as 4 packs of 100, but just a pack of 400

**Operating System:**
Windows, Mac, Or Linux

**Comment by Arufonsu** [comment] 2022-05-03 18:56
Closing this as duplicate of #786

**Closed by Arufonsu** 2022-05-03 18:56 UTC
Labels: bug, duplicate
