### ISSUE TITLE
enhancement: Remove movement speed from NPC attack handler

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1841] opened 2023-07-20 20:29 UTC
### Description

the movement speed is what is tied to the npc's attack speed, and there is no attack speed manipulator

### Intended Use-Case

separate things only, so that spell effects that affect only movement speed or only attack speed, affect npcs correctly, so to affect the npc's attack speed currently, you must change the speed of attack movement.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2023-09-01 01:39
This should be a thing for every entity (NPCs and Players !)
As it was previously discussed: https://github.com/AscensionGameDev/Intersect-Engine/discussions/1547

**Comment by Arufonsu** [comment] 2023-09-01 01:42
This should be a thing for every entity (NPCs and Players !)
As it was previously discussed: https://github.com/AscensionGameDev/Intersect-Engine/discussions/1547

Also, i believe that we should keep the same idea/conversation in one place, i know that this is meant for NPCs but honestly, the root topic of the whole thing is to split attack speed from movement speed, i would normally suggest to close this and continue where the discussion was originally started, but i'll let the maintainer to decide since is quite valid as well

**Comment by lodicolo** [comment] 2023-11-03 06:33
Effectively a dupe of #1547

**Closed by lodicolo** 2023-11-03 06:33 UTC
Labels: enhancement
