### ISSUE TITLE
Additional numeric options on variable setters

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1110] opened 2022-03-11 15:46 UTC
**Is your feature request related to a problem? Please describe.**
A lot of event potential could be unlocked by allowing developers easy access to event positions, as integers, and player levels.

**Describe the solution you'd like**
When setting a variables value, in a similar fashion to the existing "System Time (ms)" option, I would like to see the following:

- Player X
- Player Y
- Player Level
- Event X
- Event Y

It could look something like this:
![image](https://user-images.githubusercontent.com/8580915/157900897-e6eb0e35-ea7e-46a3-ba53-275442be1278.png)

**Comment by AlexVild** [comment] 2022-03-22 00:24
![image](https://user-images.githubusercontent.com/8580915/159384009-3f69884b-77aa-4661-90dc-3a3aee72f623.png)

**Comment by WeylonSantana** [comment] 2022-04-29 02:26
@AlexVild player x,y event x,y and level are params.

You can set a string variable to \param{plyrX} something like that and get the value
Try show a text "\params" maybe show all param you can get, stats too

**Comment by WeylonSantana** [comment] 2022-09-06 11:15
Duplicate of #419
I will be closing and taking additional comments to the original post

**Closed by WeylonSantana** 2022-09-06 11:15 UTC
Labels: feature request
