### ISSUE TITLE
Expand basic Variable functionality (XReq #2)

### ISSUE THREAD

**Issue by Xyseer764** [AscensionGameDev/Intersect-Engine#851] opened 2021-07-11 07:14 UTC
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to read game variables from the editor. This severely limits the engine's users, as they're unable to do things based off of the engine's data or they have to go to silly lengths to obtain some variable. Like in the past people created a purpose-made system for counting levels each time a player changes their level, instead of just being able to access that variable directly. Now, we have a condition for the level, but that's just patching a hole with paper - it's an unmodular implementation. Allowing users to write the level value to a variable would give that wanted functionality and more.

**Describe the solution you'd like**
When setting a variable the editor should have another sub-menu, which would list all important game variables. I'll list the variables I can think of here, but I've only recently discovered the engine, so there are most likely more:

- Level
`Explained above.`
- Stat
`Same explanation as Level.`
- The Count of a specific Item
`This is also implemented in a non-modular way, where we just have access to this value in conditions. When for example I wanted to create a system to take half of a player's item, I found out that it's impossible without editing the source code or doing some extremely unscalable and slow implementation that takes the player's items one by one.`
- Player X and Y position (global position would be better than local, creating a tickbox for choosing between global and local positions would be best)
`This allows the users to create zones or areas in which some event takes place.`
- Free inventory slots
`Non-modular implementation in conditions currently.`
- Health and Mana and EXP
`Useful for a lot of general things.`
- Add modulo operation
`Not directly related to changes above, but the fact that we have access to bitwise operations, but we cannot do modulo division seems really strange to me. Currently I'm using a common event that calculates the modulo value, but that's a really bad way of doing it.`

**Additional context**
This feature requires the creation of a single drop-down menu and the hooking up of each of the listed variables to the options. Its dev cost is low, but the things it enables are general. Pretty much any developer would be happy to see this feature.

**Personal Note**
I've discovered the engine recently and I'm examining its functionality for my project. I come from a Unity/Godot environment, but my plan to make an MMO made me go looking for alternatives better than just coding the entire thing myself (from my experiences, I really hate dealing with net code). I'm impressed with the engine's back-end as it handles all of the networking bull-crap I didn't want to deal with. Unfortunately, every time I try to implement something using the editor, I find it extremely lacking in basic functionality, which is why I'll be creating a few feature suggestions which I think would massively improve the engine's functionality and are really general to the entire MMORPG experience. I want to contribute to the project in the future, but the lackluster (most of the time completely absent) use of comments in the code and no code documentation multiply the amount of time I'll need to grasp the code base a hundred-fold.

**Comment by blinkuz** [comment] 2021-07-11 13:59
Having read both posts, this seems more like a request suggestion than the previous one, which was a point of view, I agree with this functionality since it would help a lot to create more complete systems with the editor, obviously it will not eliminate the need to have You have to program specific things in the source code but it can help a lot so hopefully they take it into account.

**Comment by jcsnider** [comment] 2021-07-11 14:03
So I think right now you can assign values like levels/stats to string variables, and then maybe assign those string variables into integer variables. Idk. Regardless I tend to agree that it shouldn't be that difficult.

Open for a PR on this if anyone reading is so inclined.

**Comment by WeylonSantana** [comment] 2022-09-06 10:59
I'm closing this feature request post, a good part of it is a duplicate of #419 (level, hp, mp, stat, etc), and I'll be complementing the original feature request with the extra ideas presented here.

**Closed by WeylonSantana** 2022-09-06 10:59 UTC
Labels: feature request
