### ISSUE TITLE
Korean language support issues

### ISSUE THREAD

**Issue by idm0504** [AscensionGameDev/Intersect-Engine#1080] opened 2022-02-15 08:20 UTC
I wrote a post about Korean input.

Korean is not supported properly
It's too inconvenient. Other Korean users, including myself, are uncomfortable

I hope you can properly support Korean as soon as possible.

**Comment by Arufonsu** [comment] 2022-02-15 08:40
Please don't create duplicated issue reports 😞 ...
closing this since is a duplicate of #1028

**Closed by Arufonsu** 2022-02-15 08:40 UTC
Labels: bug, duplicate
