### ISSUE TITLE
Set Range [BUG]

### ISSUE THREAD

**Issue by Kamusvalenzuela** [AscensionGameDev/Intersect-Engine#549] opened 2021-02-16 19:23 UTC
**Describe the bug**
Random Range on items doesn't work

**Version Encountered**

0.7.0.106
**To Reproduce**
1. Make a new item with set range on 5 for example
2. drop it on a map and equipp it
3. See error

**Expected behavior**
The "Set range" need to apply the random values on the character stats, but here the set range dont work

.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/51339474/108111117-073e3780-7073-11eb-8687-6aebe85cff9c.png)
![unknown (1)](https://user-images.githubusercontent.com/51339474/108111124-07d6ce00-7073-11eb-8ba3-7d544925613e.png)

**Operating System:**
All

**Comment by jcsnider** [comment] 2021-02-16 19:40
Dupe of #521

**Closed by jcsnider** 2021-02-16 19:40 UTC
Labels: bug, duplicate
