### ISSUE TITLE
bug: events name is not respecting server colors

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1259] opened 2022-05-20 04:19 UTC
**Describe the bug**
I noticed that the nicks of the Events are all in white, with black borders, and a transparent background

**Version Encountered**
0.7.1.16

**To Reproduce**
1. Create Event
3. Check and change Event Name Color on Server Colors
**Screenshot**

![image](https://user-images.githubusercontent.com/1476550/170109869-99047ca8-71ab-4039-a3a1-19ba250c2a7e.png)

Your file can be found here:
![image](https://user-images.githubusercontent.com/1476550/170109915-23339998-2159-4ac6-bd40-637babd9ad54.png)

**Operating System:**
Windows, Mac, Or Linux

**Additional context**
I think this bug came after the update #1216 or #1233

**Comment by dudevelopement** [comment] 2022-05-21 20:30
Complementing...

Events without image, end up hiding the name as well, even though they are not marked as HIDE

**Comment by Arufonsu** [comment] 2022-05-22 02:34
I couldn't reproduce this issue: NPCs name colours are working as expected when setting them up in the server side.
Are you properly following the ARGB (Alpha, Red, Green, Blue) format? that's the order used for colours in the intersect engine.

**Comment by Arufonsu** [comment] 2022-05-22 02:41
> Complementing...
> 
> Events without image, end up hiding the name as well, even though they are not marked as HIDE

Not related to this issue, but yes, i can confirm that this is happening, if you wish to get around this one, make sure to open another issue report for it.

**Comment by dudevelopement** [comment] 2022-05-22 16:56
> I couldn't reproduce this issue: NPCs name colours are working as expected when setting them up in the server side. Are you properly following the ARGB (Alpha, Red, Green, Blue) format? that's the order used for colours in the intersect engine.

was there any change in the colors.json structure?
Because after updating to that version this bug happened.
in the previous version it worked

**Comment by dudevelopement** [comment] 2022-05-22 20:20
Ah yeah.. i delete my colors.json and it generate a new, a ill open a new issue with Name Hide without image...

**Comment by dudevelopement** [comment] 2022-05-22 20:26
Test here again, the nicks of all events, both Npcs, are not working, the only thing it respects is the background color.

The font colors do not change, can you test there?

**Comment by Arufonsu** [comment] 2022-05-24 01:15
like i said:


> I couldn't reproduce this issue: NPCs name colours are working as expected when setting them up in the server side

![imagen](https://user-images.githubusercontent.com/17498701/169928656-7d5413b0-7dac-4f90-b248-d4fc82cc47d2.png)


![imagen](https://user-images.githubusercontent.com/17498701/169928596-49f87ec7-bf00-489e-b98f-52ebf5d3439b.png)

**Comment by dudevelopement** [comment] 2022-05-24 01:31
and with the EVENTS?

**Comment by dudevelopement** [comment] 2022-05-24 04:15
I discovered the error.

If you create 1 event where its image is a Tileset. The colors work, if you define his image from a sprite, the bug occurs.

**Comment by lodicolo** [comment] 2022-05-25 21:20
Fixed in 0.7.1.19

**Comment by lodicolo** [comment] 2022-05-25 21:20
Fixed in 0.7.1.19

**Closed by lodicolo** 2022-05-25 21:20 UTC
Labels: bug
