### ISSUE TITLE
bug: AoE Spell Kills trigger Npc common events on death for once.

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#1692] opened 2022-12-27 14:09 UTC
### Description

If you kill multiple enemies with an AoE spell, it will only trigger one common event. (Kill multiple things in a same time.)

### Steps to Reproduce

1. Make an aoe spell that can one shot enemies.
2. Give a npc common event on death.
3. Kill many npcs in a same time with a single aoe spell.
4. You will see it will trigger only for one time.

### Version with bug

v0.7.1.90

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2023-02-03 18:19
duplicate of #443
which has been moved over to #1498

**Closed by Arufonsu** 2023-02-03 18:19 UTC
Labels: bug, needs verification
