### ISSUE TITLE
bug: \guildva text ID not writing out

### ISSUE THREAD

**Issue by RecoStar** [AscensionGameDev/Intersect-Engine#2286] opened 2024-06-15 18:39 UTC
### Description

When you add a guild variable with a text id to call it later, it does not call back via \guildva{}

### Steps to Reproduce

Create a guild variable.
Give it a text id of "storage"
Create a map event that is a trigger "Action Button"
Add a text line that reads out guild variable:    \guildva{storage}
Trigger the map event to display text box

### Version with bug

0.8.0.170

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment] 2024-06-15 20:41
this is not a bug - the correct have a R in the end \guildvar{}

https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/5e85e605-fb9d-4f9d-9f20-9b90d71e86ae

So, confirm for me that it's not a bug

**Comment by Arufonsu** [comment] 2024-06-16 00:59
Tried to reproduce this issue, got the same results as @WeylonSantana 
Closing this as -not an issue-

**Closed by Arufonsu** 2024-06-16 00:59 UTC
Labels: not an issue

**Comment by RecoStar** [comment] 2024-06-16 06:33
Thanks, did not know it was \guildvar{} as in the editor it shows as \guildva{}

![guildva](https://github.com/AscensionGameDev/Intersect-Engine/assets/25243860/b1e4ab64-e46f-4ed1-9e7b-0715e053e819)
