### ISSUE TITLE
Automatic rain system on maps that are not Internal

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1030] opened 2022-01-02 19:42 UTC
**Is your feature request related to a problem? Please describe.**
It would be really cool and easier to configure, if there was a global, automatic rain system, as well as the timetable, to have one for the chance and amount of rain to fall around the world.

**Describe the solution you'd like**
You can configure an animation, chance and sound of rain, in the editor, like Time, something that synchronizes with the server and everyone has the same rain anywhere in the world.

**Comment by Cheshire92** [comment] 2022-01-05 10:57
I'd prefer a weather system in general that you can tie to maps rather than a single animation per map if this is to be a thing.

**Comment by WeylonSantana** [comment] 2022-09-06 11:10
Considering that in this f.r "conditions" are being asked for a weather to happen this makes a duplicate of #885.
I'll be closing and moving the cheshire comment to the original post, to be considered if this is to be a thing one day

**Closed by WeylonSantana** 2022-09-06 11:10 UTC
Labels: feature request
