### ISSUE TITLE
Crafting Effects and Conditions (XReq #3)

### ISSUE THREAD

**Issue by Xyseer764** [AscensionGameDev/Intersect-Engine#852] opened 2021-07-11 08:10 UTC
**Is your feature request related to a problem? Please describe.**
The current crafting system is not scalable if the developer intends to implement any sort of conditions or skill requirements. As an example let's take a crafting table of 12 crafts. If we want each item to have some unique condition then we'd need to create 2^12 crafting tables (allowed or disallowed state for each craft required). Another thing is that crafting doesn't allow us to cast effects - this severely limits options. If you wanted to for example grant crafting experience for each time you craft something, you're out of luck.

**Describe the solution you'd like**
- Condition
`Add the ability to add condition lists for each craft. Also add a checkbox on whether or not we'd like to hide the item from a workstation or simply gray it out as an option when the condition's not fulfilled.`
- Common Event after craft
`Add the ability to trigger a common event after a craft successfully completes.`
- IN-GAME Crafting Station
`Do not show items that don't have their condition fulfilled or gray them out as an option. If all options are hidden (not grayed out, though) throw some default message to chat saying something like "You're unable to use this crafting station.", as we shouldn't show an empty crafting menu to the player.`

**Additional context**
This proposed feature's not complicated and it would grant a lot more options to the user in regards to the crafting system. It's also very general, so it'd be of use to pretty much any game that uses crafting.

**Personal Note**
I've discovered the engine recently and I'm examining its functionality for my project. I come from a Unity/Godot environment, but my plan to make an MMO made me go looking for alternatives better than just coding the entire thing myself (from my experiences, I really hate dealing with net code). I'm impressed with the engine's back-end as it handles all of the networking bull-crap I didn't want to deal with. Unfortunately, every time I try to implement something using the editor, I find it extremely lacking in basic functionality, which is why I'll be creating a few feature suggestions which I think would massively improve the engine's functionality and are really general to the entire MMORPG experience. I want to contribute to the project in the future, but the lackluster (most of the time completely absent) use of comments in the code and no code documentation multiply the amount of time I'll need to grasp the code base a hundred-fold.

**Comment by jcsnider** [comment] 2021-07-11 13:10
Common event after craft is already done in #813 

Crafting requirements per craft is something that I've already done, but hasn't been brought in yet. Marking this as todo for B7

**Comment by da-rulez** [comment] 2021-08-10 21:51
Including the hiding of crafts you don't meet requirements for? @jcsnider

Would be nice to have crafts you don't have the items for in red and the ones you don't meet reqs to not show up at all! 

What's the plan?

**Comment by Arufonsu** [comment] 2022-07-06 18:32
Reopening this since the issue isn't completly resolved, the crafting requirements per craft will be supplied by #1346

**Closed** 2022-08-31 19:56 UTC
Labels: feature request
