### ISSUE TITLE
bug: Event triggers "Guild Member Join/Left/Kicked" not funcitoning.

### ISSUE THREAD

**Issue by PyroTech03** [AscensionGameDev/Intersect-Engine#1817] opened 2023-05-26 02:57 UTC
### Description

Using common event with triggers of "Guild Member Join/Left/Kicked" does not trigger the event.

### Steps to Reproduce

1. Create Guild Variable "Member Count"
2. Create Common Event
3. Set trigger to "Guild Member Joined"
4. Command: Set Guild Variable Guild Member Count (Add 1)

To confirm the bug

1. Create event with /command trigger to check the variable.

### Version with bug

0.7.2.0

### Last version that worked well

0.7.1.119

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by PyroTech03** [comment] 2023-05-26 03:15
Not sure if it's relevant or not, but it came up while I was testing.....

`--------------------------------------------------------------------------------
2023-05-26 03:12:25.764 [Error] Received unhandled exception from System.Threading.Thread.

--------------------------------------------------------------------------------
2023-05-26 03:12:25.767 [Error] InvalidOperationException: Nullable object must have a value.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Intersect.Server.Entities.Events.CommandProcessing.ProcessCommand(SetGuildBankSlotsCommand command, Player player, Event instance, CommandInstance stackInfo, Stack`1 callStack)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid6[T0,T1,T2,T3,T4,T5](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Intersect.Server.Entities.Events.CommandProcessing.ProcessCommand(EventCommand command, Player player, Event instance)
   at Intersect.Server.Entities.Events.Event.Update(Int64 timeMs, MapController map)
   at Intersect.Server.Entities.Player.Update(Int64 timeMs)
   at Intersect.Server.Maps.MapInstance.UpdateEntities(Int64 timeMs)
   at Intersect.Server.Maps.MapInstance.Update(Int64 timeMs)
   at Intersect.Server.Core.LogicService.LogicThread.UpdateMap(MapInstance mapInstance, Boolean onlyProjectiles)


--------------------------------------------------------------------------------`

**Comment by WeylonSantana** [comment] 2023-05-26 11:41
I downloaded the latest version and did not find a bug, I will close it as it is not a bug, if it has steps on how to do it, video showing how to reproduce the bug, We can open it again.

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/f9e3b8cd-0e43-4ca3-9105-8095d0d82150)
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/f5008f64-51e8-4532-8064-8f1fac38da7c)
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/fac30774-f60f-4d6a-b467-576f43a046bd)

The mentioned types of events above are not only working, they are also activated for all online members.
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/c3cccd56-09b2-4198-8a02-fa1202acd88b)

**Closed by WeylonSantana** 2023-05-26 11:41 UTC
Labels: bug, needs verification
