### ISSUE TITLE
bug: port forwarding not working?

### ISSUE THREAD

**Issue by darkjezza** [AscensionGameDev/Intersect-Engine#1810] opened 2023-05-10 07:16 UTC
### Description

I'm having trouble port forwarding

i also set UPnP to false same thing

![Screenshot_1](https://github.com/AscensionGameDev/Intersect-Engine/assets/80877059/a888a6d2-ae66-46d7-908f-3d6b4cce72eb)
![Screenshot_2](https://github.com/AscensionGameDev/Intersect-Engine/assets/80877059/0482b3d8-1708-4899-b70a-2af8138c77b6)

### Steps to Reproduce

add port to firewall
add port to router
launch server
check port on port checker
result: closed port

### Version with bug

0.7.2-beta.15

### Last version that worked well

Unkown

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

no

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by darkjezza** [comment] 2023-05-10 07:33
there must be something wrong because i went to try the Orion plus engine
and i was able to open the port

**Comment by Arufonsu** [comment] 2023-05-11 01:18
> i also set UPnP to false same thing

You don't seems to understand what UPnP is for (?) please have a read here: https://en.wikipedia.org/wiki/Universal_Plug_and_Play

this is the issue tracker, not a place to ask questions, for questions use https://github.com/AscensionGameDev/Intersect-Engine/discussions/categories/q-a and/or https://www.ascensiongamedev.com/forum/53-questions-answers/

> add port to firewall

Why? you are adding an exception for the server on what? Windows? Linux? show us screenshots or steps on how you did this.

> add port to router

?... to router? you are supposed to set port forwarding of the UDP port 5400 to the machine that's hosting intersect, also, you didn't provided any screenshot on your configurations, you neither show up if you are using UDP ports as the port protocol type to forward.

> launch server
> check port on port checker
> result: closed port

> there must be something wrong ...

This is more likely an issue on your end it seems? here on three terminal end i have, either Windows, Linux (Manjaro atm), even as a Docker container, the intersect server 0.7.2-beta.15 is doing well and handles connections to the public network if properly configured.

> there must be something wrong because i went to try the Orion plus engine and i was able to open the port

This comments it's not helping at all, i don't know how "Orion plus" works, i don't even personally what that project is like, this repository belongs to a different project, perhaps Orion plus used TCP ports instead of UDP ports (just assuming this) and you are mixing up apples along with patatoes in the oven? anyways, we have documentation for this right here: https://docs.freemmorpgmaker.com/en-US/deploy/forwarding/

i'm closing this for now as i'm unable to reproduce with the details provided, plus, the report itself lacks of critical information (such as configurations, type of ports supposedly forwarded) and it seems to be more of a support question that should be addressed elsewhere as i pointed out already.

**Closed by Arufonsu** 2023-05-11 01:18 UTC
Labels: bug, needs verification
