### ISSUE TITLE
bug: editor FPS loss when using cliff tiles

### ISSUE THREAD

**Issue by Thomasfds** [AscensionGameDev/Intersect-Engine#796] opened 2021-06-22 13:28 UTC
**Describe the bug**
Hello !

We have a problem with our editor, we currently have 150 maps which are all linked.

We have a huge drop in fps which makes it impossible to continue to map when using mask 1 and 2 on 90% of the linked maps.

We have tried other project, 300 maps linked no problem ..

I am raising the issue to see if others have already had it or not and if this can be fixed?

Update :
https://github.com/AscensionGameDev/Intersect-Engine/issues/796#issuecomment-866904296
this problem is due to the cliff option

**Version Encountered**

V0.7.0.121

**To Reproduce**
Here is a video of the problem :

https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/48d48f91d0f5f6964f1bf3cfec7aca86.mp4

**Operating System:**
Windows 10

**Comment by Thomasfds** [comment] 2021-06-23 14:48
Additionnal data :
All version (b6 to b7) have the bug.

When i create a cliff with default tileset whether it be layer 1, 2,3,4 or 5 all bug !

**Comment by jcsnider** [comment] 2021-07-03 13:04
Turning off tile preview would probably help a lot just while placing cliffs.

The logic for cliffs is more complex than all other autotile types because cliffs need to know exactly where they start and end, even if it's across maps. The logic which slows things down are [here](https://github.com/AscensionGameDev/Intersect-Engine/blob/development/Intersect%20(Core)/GameObjects/Maps/MapAutotiles.cs#L664-L732) and [here](https://github.com/AscensionGameDev/Intersect-Engine/blob/development/Intersect%20(Core)/GameObjects/Maps/MapAutotiles.cs#L2238-L2319)

I invite anyone to try to optimize those sections above. Not something I am interested in tackling right now.

**Comment by WeylonSantana** [comment] 2022-06-20 23:03
This is not a bug, but it will be left open so an extra check can be done to prevent it from happening again.

**Comment by lodicolo** [comment] 2023-11-03 04:59
With the WinForms editor deprecated this is probably never getting fixed so I am closing this.

If someone actually decides to fix this, feel free to re-open this once you open a PR.

**Closed by lodicolo** 2023-11-03 04:59 UTC
Labels: bug, help wanted, verified
