### ISSUE TITLE
bug: /param event commands not working

### ISSUE THREAD

**Issue by TheBearWannabe** [AscensionGameDev/Intersect-Engine#1228] opened 2022-04-26 23:13 UTC
**Describe the bug**
When using the /param command within an event/common event, it's ignored and only the preceding command is displayed.

**Version Encountered**
0.7.1.9-beta-prerelease

**To Reproduce**

1. Open Intersect Editor. 
2. Under the top menu, navigate to Game Editors > Common Events
3. In the popup menu, create a new common event (RP Emote)
4. Double click on the newly created event, and double click within the commands box.
5. Under Dialogue, select "Add Chatbox Text"
6. In the settings, create the text as "\pn \param" (No quotes of course) and click OK.
7. Under "Commands" in the lower right hand corner of the event window, add /e to trigger the command in game.
8. Launch game, and use the command "/e is testing this command" in the chatbox
9. The command only displays the character name (\pn) 

**Expected behavior**
When using something like "\pn \param" it should append the message added by the player at the end. In this example, if the player entered "/e tests the issue" it would display in the chat as "(name) tests the issue"

**Screenshots**
![param0](https://user-images.githubusercontent.com/98631067/151646839-3b2a9bac-8f2e-40cf-a342-36bb9c493917.png)
https://user-images.githubusercontent.com/98631067/165407622-d3b7cb7f-5a6c-487f-9e01-987bf41dd64d.mp4

**Logs**
No error logs

**Operating System:**
Windows 11

**Additional context**
This seemed to be closed previously but came back in the beta, just wanted to report it again. Thanks!

**Comment by Arufonsu** [comment] 2022-04-27 21:28
closing as a dupe of #1057
you don't have to report it again if the issue report has already been made before, the same conversation may still continue in the already closed issue report.

**Closed by Arufonsu** 2022-04-27 21:28 UTC
Labels: bug, duplicate
