### ISSUE TITLE
bug: Camera Shaking When Moving Left or Right at World Scale 2,3,4

### ISSUE THREAD

**Issue by TimtyG** [AscensionGameDev/Intersect-Engine#1974] opened 2023-10-16 09:11 UTC
### Description

The issue is most probably a camera shaking. This is observed when the player character moves to the left or right while the game is zoomed and works fine on World Scale 1. 

Attaching video.

https://github.com/AscensionGameDev/Intersect-Engine/assets/36088127/7cd0cd5a-d6a7-425e-9786-09ef2c9bc658

### Steps to Reproduce

1. Make sure the game is running.
2. Set the world scale to 2/3 or 4 (zoom level).
3. Control the player character to move to the left or right.
4. Observe the camera's behavior during the movement.

Expected Behavior
The camera smoothly follows the player character's movement when they go left or right.

### Version with bug

0.7.2.0

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

No.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by theceltos** [comment] 2023-10-30 16:27
I tested it here and the anomaly actually happens...

**Comment by Arufonsu** [comment] 2023-11-08 23:26
Unable to reproduce with [0.8.0-beta.63](https://github.com/AscensionGameDev/Intersect-Engine/releases/tag/v0.8.0-beta.63)

my attempt to reproduce at x4 :

https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/2dbac337-859e-4ca7-89c1-84d7111a40eb

@Richy1111 's video from discord:

https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/6331e34e-a0e5-4fbb-a71a-95e6d90d9b33

**Comment by Arufonsu** [comment] 2023-11-09 01:05
Actually, closing as "complete" since it was apparently an issue back then with 0.7.2.0 ish

**Closed** 2023-11-09 01:04 UTC
Labels: cannot be reproduced, not an issue

**Comment by theceltos** [comment] 2023-11-09 22:36
For me the bug remains

**Comment by Arufonsu** [comment] 2023-11-10 18:02
> For me the bug remains

how so? can you confirm that the issue is still happening with 0.8.0-beta.63?
if so, can share over a video with steps to reproduce, and showing off that you are actually using 0.8.0-beta.63?

**Comment by Arufonsu** [comment] 2023-11-10 18:04
> For me the bug remains

how so? can you confirm that the issue is still happening with 0.8.0-beta.63?
if so, could you please share over a video with steps to reproduce, and showing off that you are actually using 0.8.0-beta.63?

**Comment by theceltos** [comment] 2023-11-11 00:12
> > For me the bug remains
> 
> how so? can you confirm that the issue is still happening with 0.8.0-beta.63? if so, could you please share over a video with steps to reproduce, and showing off that you are actually using 0.8.0-beta.63?

Camera shake xD

https://youtu.be/3a_QqoHfOkk

**Comment by theceltos** [comment] 2023-11-11 00:14
Camera Shake :(

https://youtu.be/Rhb0Y2dUOjY

**Comment by TimtyG** [comment] 2023-11-28 17:52
Can confirm it happens again on 0.8.0-beta.114.
