### ISSUE TITLE
bug: cannot click into quest when hovering over the title, only when you hover over the line without text

### ISSUE THREAD

**Issue by Gokwol** [AscensionGameDev/Intersect-Engine#1265] opened 2022-05-24 01:10 UTC
**Describe the bug**
When you hover over a quest, you can't click on it unless you move off of it.

**Version Encountered**

0.7.1.17

**To Reproduce**
1. Go to the quest log is a quest in progress
2. Hover over the quest title (not the line where the quest is)
3. The highlight will not show up, and you cannot click into the quest.

**Expected behavior**
As you hover over the title, you should be able to click into it. This makes it less confusing.

**Screenshots**
![b31f4b9ebbc0e0e2d199923621ae42bf](https://user-images.githubusercontent.com/64770171/169928434-e9170900-2e93-4d03-a1ed-8e6b440bbb8d.gif)

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**
This is a quest in progress, I don't know if this will replicate for completed/not started quests.

**Comment by dudevelopement** [comment] 2022-05-24 01:27
its duplicate of #1207

**Closed** 2022-05-24 01:30 UTC
Labels: bug, duplicate

**Comment by Gokwol** [comment] 2022-05-24 01:38
@Arufonsu
![Screenshot_58](https://user-images.githubusercontent.com/64770171/169931063-d573c709-0589-4557-8408-711278046de9.png)

Maybe cause he stole my screenshot lmao?

**Comment by Gokwol** [comment] 2022-05-24 01:40
y'all are terrible devs lmfao

**Comment by jcsnider** [comment] 2022-05-24 02:23
This isn't stackoverflow, you don't get points or credit for bug reports, and it does us no good to have duplicates. It does, however, help to know how long a bug has existed while unsolved. 

You could have searched and appended the screenshot to the other report because this was, infact, a duplicate. 

Regardless it's been added to the other report and you've been credited for the additional info/contribution. 

Moreso than devs, we are volunteers with limited time. If you don't like how we run the repo feel free to look at other engines but there's no need to be insulting.

**Comment by Gokwol** [comment] 2022-05-24 02:29
> This isn't stackoverflow, you don't get points or credit for bug reports, and it does us no good to have duplicates. It does, however, help to know how long a bug has existed while unsolved.
> 
> You could have searched and appended the screenshot to the other report because this was, infact, a duplicate.
> 
> Regardless it's been added to the other report and you've been credited for the additional info/contribution.
> 
> Moreso than devs, we are volunteers with limited time. If you don't like how we run the repo feel free to look at other engines but there's no need to be insulting.

I understand this, but the developer was being hostile and accusing me, it felt unwelcoming. I thank them for owning up to the mistake, it's not about the credit or a duplicate bug report to me, I just want to not feel accused or like I've purposely done something to cause an improper flow or flood of bugs. I apologize for duplicating and acknowledge that you guys are volunteers, but I simply find a bug and use the Help - Report a Bug button within the client to quickly get to it and post.

I love this engine - it is not the point for me to go find a different engine, I would have no problem if they stated "Duplicate report" etc., but there was an accusation of purposely duplicating a report by stealing someone else's GIF which I proved was mine. I would have appended it if I knew, but like I said I just use the client links.
