### ISSUE TITLE
bug: status isHiden shouldn't be identified by monsters.

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1273] opened 2022-05-28 18:19 UTC
**Describe the bug**
Characters with isHiden status through events should not detected by monsters.

**Version Encountered**
0.7.*

**Expected behavior**
As its name says *isHiden*, it should not be affected by any entity, even because it is in a hidden status.

**Operating System:**
Windows, Mac, Or Linux

**Additional context**
The isHiden method is a way to protect the player from other monsters during a cutscene or even a Staff player who wants to walk around unnoticed.

**Comment by lodicolo** [comment] 2022-05-28 22:09
Dupe of #1052

**Closed by lodicolo** 2022-05-28 22:09 UTC
Labels: bug, duplicate

**Comment by dudevelopement** [comment] 2022-05-28 22:25
@lodicolo I changed the name, so it is no longer duplicated

**Comment by lodicolo** [comment] 2022-05-28 22:31
@dudevelopement The two issues are functionally the same. I didn't look at the title to determine they were a dupe I looked at the substance of the issues.

**Comment by dudevelopement** [comment] 2022-05-29 01:23
Ah certo

**Comment by dudevelopement** [comment] 2022-05-29 01:23
Ah ok
