### ISSUE TITLE
bug: Player Block with a Shield and be kicked for spam api

### ISSUE THREAD

**Issue by GarozoneISE** [AscensionGameDev/Intersect-Engine#1682] opened 2022-12-11 06:01 UTC
### Description

Hey, It's my second report and I don't know if I do this correctly but here : 

- When a player has a shield and uses it to block, they will start having a blocking animation but not constently/loop, creating a spam api that kicks them. (I'm not kick in the video because I'm admin.)

Link Video : https://youtu.be/8J1dSN1rON8

### Steps to Reproduce

Required : Player only
Step 1 : Have a item shield
Step 2 : Use the block with shield
Step 3 : Be kicked by the server for spam api

### Version with bug

v0.7.1.088

### Last version that worked well

Unknow

### Affected platforms

Windows

### Did you find any workaround?

I don't have a workaround for that, just not use the block.. sadly

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2022-12-11 15:17
You will need to provide more accurate steps on how to reproduce this, perhaps, share a video with a player getting kicked by... the API? _that doesn't makes much sense to me_ since in your video you are **in game** ... 
anyways: i couldn't reproduce this issue with a non-admin account. 

PS: As for the not constently/loop shield animation, i'm already covering that unwanted behavior at #1674 (feel free to test that up!)

**Comment by Arufonsu** [comment] 2023-04-16 23:49
Closing this for now, since no method to properly reproduce this has been provided yet since Dec 11, 2022.

Will reopen if the OP or anyone else who wishes to collaborate, shares over a video that shows up the reported issue.

**Closed by Arufonsu** 2023-04-16 23:49 UTC
Labels: bug, cannot be reproduced
