### ISSUE TITLE
bug: DoTs persist after Player Death

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1714] opened 2023-01-29 18:52 UTC
### Description

A player dying when a DoT has been cast on them and active prior to death with have said DoT remain active after the player has died. This seems to only happen when the DoT spell cast on the Player was the cause for player death.

This bugs seems in relation to [issue #743](https://github.com/AscensionGameDev/Intersect-Engine/issues/743)

this bug has been in the engine for as long as I can remember

From Discord Bugs chat:
@WeylonSantana "the problem is that the npc can cast spell on you after you die, I managed to make him do that regardless of the distance. It doesn't even have to be a dot, it can be any spell, with duration."

### Steps to Reproduce

1. Create long duration DoT spell with a tick interval
2. Have an NPC cast that spell on the player to kill him
3. DoT remains on player after death (this occurrence is not 100% it seems) 

### Version with bug

v0.7.1.88

### Last version that worked well

As far back as I can recall

### Affected platforms

Windows, macOS

### Did you find any workaround?

Set up /respawn common event to Give Player Vitals +HP a few times to prevent the player double dying.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment] 2023-01-29 19:15
Yeah, any spell with duraction, not just the dot spells, any spell.

**Comment by WeylonSantana** [comment] 2023-01-29 19:16
The problem is on update method in entities.cs, after player die the "//cast timers if."

**Comment by Arufonsu** [comment] 2023-02-03 18:05
Closing as a duplicate of #743 
If you want to continue with this report, please attach screenshots of your full spell/projectile configurations and bring them over along with your report details to the issue discussion at #743

Since Weylon confirms that this is actually happening, i'll reopen #743 and label it as verified so the bug resolution and discussion continues where it started.

**Closed by Arufonsu** 2023-02-03 18:05 UTC
Labels: bug, needs verification
