### ISSUE TITLE
/command causes client disconnection.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#416] opened 2020-10-23 19:14 UTC
**Describe the bug**
Removing bound items through an event causes the client to disconnect.

**Version Encountered**
0.6.2.447

**To Reproduce**

1. Create a common event whose sole function is to remove an item from the player, item bound.
2. Place the activation of the command by /
3. You will take disconnection.
4. No client logs are generated.

**Expected behavior**
I understand that bound items cannot be sold, deposited in bank or dropped. But events (as far as I can remember), they always had sufficient authority to remove any item, even bound.

**Screenshots**
no need

**Logs**
no anormal logs

**Operating System:**
Windows

**Comment by WeylonSantana** [comment] 2020-10-23 20:21
Edition: the bug is not in removing bound items with event. It's in typing any /command within the game.
I tested typing normally in the game and everything is normal. However any /command I take disconnect. Including the commands that have been there for months that have never been modified. I don't even need to type real commands, whatever I type, if there is a "/" before, I take disconnect.

![image](https://user-images.githubusercontent.com/63019821/97049835-b8641380-1552-11eb-93e8-0c8797305fcb.png)

Server Logs Look at the recent:

**Comment by Cheshire92** [comment] 2020-10-24 07:28
I'm unable to reproduce this on the prerelease branch.
Does this happen on non-event commands as well?

**Comment by WeylonSantana** [comment] 2020-10-24 13:32
@Cheshire92 I am beginning to add that this error is something related to the server and not an error of the intersect.  Until the day before yesterday, I used the normal / commands, then yesterday there was a lack of energy there. When it returned it started to present this error.  I'm also seeing what to do.  Why is it impossible for an error to start this way, since before everything was normal in the same version.  Did something maybe corrupt? if you want i can give you my client.  maybe it's related to the fact if I keep doing edits on an online server and not offline something like that.

**Comment by Cheshire92** [comment] 2020-10-24 20:05
I think the issue would be on the server side, not the client.
I've not been able to reproduce this though, did it start happening when you added another common event?

**Comment by WeylonSantana** [comment] 2020-10-24 22:51
@Cheshire92 I understand. So far I remember the following,
the day before yesterday: everything was normal, I made edits, used event commands and everything.
yesterday there was a power outage where the machine is on, when it came back on and from there the commands no longer worked.
today I tried to delete the player data, and start and still does not work.

It does not have to be an event-related command. Just type "/".
Initially, yes, I thought it was related to events, but from then on I started typing / and anything (/54, /wef, /, /12b34) any attempt to type / in the chatbox causes the disconnection.
I haven't tested typing / after words or things like that. But typing / at the beginning, and after that anything, related or not to events, causes the client to disconnect.

**Comment by WeylonSantana** [comment] 2020-10-24 22:51
No error is reported on the client or in the client logs. only on the server which are the logs above.

**Comment by WeylonSantana** [comment] 2020-11-02 19:42
@Cheshire92 @jcsnider please close this bug. I upgraded to version 450 today and the bug appears to have been fixed. Or if something had been corrupted in mine, switching to version 450 seemed to fix it.

**Comment by Cheshire92** [comment] 2020-11-06 09:43
Closing as requested then.

**Closed by Cheshire92** 2020-11-06 09:43 UTC
Labels: bug
