### ISSUE TITLE
Missing Resources: The Resources are not included with the newest release.

### ISSUE THREAD

**Issue by nmorgan350z** [AscensionGameDev/Intersect-Engine#1833] opened 2023-07-14 06:11 UTC
### Description

Missing key resources to run both the editor and client. You will have many newcomers that will have a problem after they have compiled the code. i.e Client will load with a black screen, and editor will be missing tilesets, and key components. 

### Steps to Reproduce

Its not really a bug just missing files needed after a fresh compile.

### Version with bug

Latest Source Release

### Last version that worked well

Latest Source Release

### Affected platforms

Windows, macOS, Linux

### Did you find any workaround?

Yes, downloaded another release that included the resources, and copied those files. But for those that don't realize that this is going on, will run in to a multitude of problems.

*  Client won't load at all, and if you copy the resource folder from the current github download release. You will receive
    a black screen.
*   Same process for the editor as well. You can load the editor, but none of the assets will be in the resource file.

I'm not really sure if this considered a bug. But I thought I'd note this for those having problems after a fresh/new compile.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2023-07-15 00:21
Just checked out the latest release
https://github.com/AscensionGameDev/Intersect-Engine/releases/tag/v0.7.2-beta.21

![imagen](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/76dc4597-fbe9-48d8-8758-69248b04121c)

![imagen](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/13cfdd9c-c6a8-45b5-bc58-477c1d4daa17)

And everything it's there!

Also, if you are running your own compilations and walk into such terrain, you should do your own research and organize the assets by yourself, regardless, this is the repo and branch you should look after: https://github.com/AscensionGameDev/Intersect-Assets/tree/main_full

Closing as not planned since this is not a bug nor an issue.

**Closed by Arufonsu** 2023-07-15 00:21 UTC
Labels: bug, needs verification
