### ISSUE TITLE
Event "Play Animation" selection square does not move

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#287] opened 2020-08-10 21:05 UTC
**Describe the bug**
When trying to select an animation, the red square does not appear when selecting which tile it will appear, note in the video sent.
Spawn a monster works, but in the animation, it doesn't work.

**Version Encountered**
0.6.2

**To Reproduce**
VIDEO: https://ascensiongamedev.com/resources/filehost/4955ef87b776b260b58c3d4183fc3986.mkv

**Operating System:**
Windows

**Comment by TheCeltos** [comment] 2020-08-12 19:57
I fixed it on my branch.

**Comment by lodicolo** [comment] 2020-08-24 04:25
Duplicate of #232

**Closed by lodicolo** 2020-08-24 04:25 UTC
Labels: bug, duplicate
