### ISSUE TITLE
bug: Spells castable outside of defined Cast Range

### ISSUE THREAD

**Issue by Gallus-RSPS** [AscensionGameDev/Intersect-Engine#1781] opened 2023-03-25 22:37 UTC
### Description

I've set a spell to have the Cast Range as 4 tiles. I am able to cast the spell outside of a 4 tile range from the target. I'm unsure if this is actually a bug or I am misunderstanding the use of the Cast Range.

### Steps to Reproduce

1. Make a spell

2. Set the following target type:
![imagen](https://user-images.githubusercontent.com/17498701/232593713-ac877781-f67c-4a9b-be6e-7b630551f9c2.png)

3. Set the Cast Range
![imagen](https://user-images.githubusercontent.com/17498701/232595630-ab5a78b7-b3c1-4ea6-8c2f-e681cdb0ed4e.png)

4. Try to cast the spell outside of the defined Cast Range

### Version with bug

0.7.1.120-beta Full

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

I have not found any workaround for this.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2023-04-17 19:59
Updated steps to reproduce. OP didn't mentioned this: ![imagen](https://user-images.githubusercontent.com/17498701/232593713-ac877781-f67c-4a9b-be6e-7b630551f9c2.png)

Tested with 0.7.1.120: made a spell with  `range: 2`

![imagen](https://user-images.githubusercontent.com/17498701/232596539-61106e40-8602-47d0-88de-28518e0e9c1b.png)

Test: Casting at 8 tiles ish of distance:

![imagen](https://user-images.githubusercontent.com/17498701/232596430-cb541035-3917-4e7f-be84-bc3ffe7a09b6.png)

Test: Casting the spell nearby the enemy (within 2 tiles) ; should display a face animation over while casting:

![imagen](https://user-images.githubusercontent.com/17498701/232595165-81ce81b7-dd5f-49a3-813e-77c25201a934.png)

Anyway, so far I am unable to reproduce with the information provided so im closing this for now, will reopen if someone manages to capture it in a video with reproducible steps.

**Closed by Arufonsu** 2023-04-17 19:59 UTC
Labels: bug, needs verification
