### ISSUE TITLE
[Error] PLAYERDB: 10000

### ISSUE THREAD

**Issue by TheCeltos** [AscensionGameDev/Intersect-Engine#290] opened 2020-08-24 00:30 UTC
**Describe the bug**
I don't know how to cause this, but it happens after the server has been on for a while, it seems to happen only on Windows.
Server closes connection and shows the error.

**Version Encountered**
0.7.0

**To Reproduce**
IDK

**Logs**
[playerdbThe Celtos Server-2020_08_22-21_07_08_036.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5115241/playerdbThe.Celtos.Server-2020_08_22-21_07_08_036.log)

**Operating System:**
Windows 10 PRO

**Comment by lodicolo** [comment] 2020-08-24 03:50
Duplicate of #120

**Closed by lodicolo** 2020-08-24 03:50 UTC
Labels: bug
