### ISSUE TITLE
bug: npc walks to the top edge of the map then stops

### ISSUE THREAD

**Issue by darkjezza** [AscensionGameDev/Intersect-Engine#1793] opened 2023-04-25 09:12 UTC
### Description

on the build 0.7.1.120-beta, when npcs are randomly moving will walk to the top edge of the map then stops
this does not happen on the stable build

### Steps to Reproduce

1. create npc
2. set npc to randomly move
3. set walking speed to 1
4. add npc to spawn randomly on map

### Version with bug

0.7.1.120

### Last version that worked well

0.7.0.143

### Affected platforms

Windows, I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2023-04-25 15:37
dupe of #1766 so i'm closing this for now, also: no additional method to properly reproduce this has been provided in comparison to the original post. Refer to ##1766 if you manage to provide a video or more detailed steps to reproduce.

**Closed by Arufonsu** 2023-04-25 15:37 UTC
Labels: bug, needs verification
