### ISSUE TITLE
bug: Craft All sometimes doesn't Craft last 2 batches

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1718] opened 2023-01-29 20:08 UTC
### Description

This bug doesn't seem to always trigger, but does often enough.
The last 2 batches on a Craft All craft sometimes stops at (2) remaining batches with Craft All button greyed out.
The player must click 'Craft' on the lat 2 batches to finish.

https://user-images.githubusercontent.com/110916959/215352856-e43111d6-b732-42d8-bcf5-de2f8c305612.mp4

### Steps to Reproduce

1. Create a recipe (2+ ingredients seems to trigger more often)
2. Craft a bunch of batches with more then 3 batches remaining

### Version with bug

v0.7.1.88

### Last version that worked well

Unknown

### Affected platforms

Windows, macOS

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2023-09-10 15:19
Closing this since no update has been given on this for a while and a lot of updates have involved crafting as today ;
Please let us know if this issue persists and if you manage to reproduce this again so we can tackle this down along, regards !

**Closed by Arufonsu** 2023-09-10 15:19 UTC
Labels: bug, cannot be reproduced
