### ISSUE TITLE
Small reordering in item editor

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1014] opened 2021-11-06 01:05 UTC
**Is your feature request related to a problem? Please describe.**
This is a very silly thing, but I think it's better than the box organization, it could be another way

**Describe the solution you'd like**
current form:

Can drop           can guild bank
Can bank           can bag
Can trade          can sell

best way i believe
Can drop    Can bank
Can trade    can guild bank
can sell       can bag

**Additional context**
This way everything related to "storing item" is only in one side.
It's very very very very silly, but I think it would be better

**Comment by lodicolo** [comment] 2022-09-25 01:42
Duplicate of #1490

**Closed** 2022-09-25 04:39 UTC
Labels: enhancement
