### ISSUE TITLE
bug: single stackable item from inventory to the bank

### ISSUE THREAD

**Issue by GarozoneISE** [AscensionGameDev/Intersect-Engine#1681] opened 2022-12-11 05:47 UTC
### Description

Hi, it's my first time for report a bug and I'm not english (I'm sorry for my disaster language) ; 

I found this bug randomly : 

I don't know what's going on, I just want to move my stackable item (potion) to the same item in my bank and some of those same items disappeared suddently
Link (1) : https://youtu.be/knqO2je_GAU

And now, if entierly of my items stacked disapeared in the bank, the slot in my bank is broken and I can't use this slot anymore : 
Link Video (2) :  https://youtu.be/3SLylQVr8y0

### Steps to Reproduce

Step 1 : Drag a stackable item to the bank like a potion or other item (Stackable only) (First Video)
Step 2 : Drag the same item through the inventory into the same slot of the same item in the bank (First Video)
Step 3 : You have the bug and item disapear randomly or/and create randomly too a broken slot in the bank and make it unusable (Second Video)

### Version with bug

v0.7.1.088

### Last version that worked well

Unknow

### Affected platforms

Windows

### Did you find any workaround?

You just shouldn't drag an item from your inventory onto a bank slot with a stackable item, otherwise it would create this bug and probably broke your bank slot. 

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2022-12-11 15:35
Tested and verified.... 😞 pretty sure that we had this behavior working as intended not long ago, whenever we dragged an stackable item that contains == 1 of that item, the slider shouldn't appear, but question prompt instead, while the slider should appear only whenever we drag in stackables with > 1 of such item.

**Comment by Arufonsu** [comment] 2022-12-11 18:31
Tested and verified. As for this issue report, I'll open a PR that fixes the issue shown in the first video, if the issues you describe in the **second** video persist, please open *another issue report* with the proper details. I haven't been able to reproduce what's going on in the second video you posted, so let's tackle down these issues one by one 👍🏽

**Comment by Arufonsu** [comment] 2023-02-03 17:22
Just to clarify the issues shown in the video:

- non stackable items are being placed over other non stackables without the proper checks, which leads to glitched slots.
- stackable items of the same kind aren't properly checking if the slot where the item is about to be deposited is full (max bank stack value isn't considered), so when the max value is ignored, the items are lost / slots glitches out.

Just opened a PR that should fix the reported unwanted behaviors, please feel free to give this a try as the feedback on wether this fixes the issue or nor will be quite useful to tackle this down. Also please, consider recreating the characters with the glitched banks when testing with this PR, since it won't fix the damaged done by the previous code.


here's an example of what the outcome should be like:


https://user-images.githubusercontent.com/17498701/216666314-28f7f2bb-a2f8-48a6-bedf-ad1cbea53fc7.mp4

**Closed** 2023-10-29 22:21 UTC
Labels: bug, help wanted, verified
