### ISSUE TITLE
bug: EquipmentOnHitTriggers when using spells

### ISSUE THREAD

**Issue by EspectroW94** [AscensionGameDev/Intersect-Engine#2240] opened 2024-05-04 22:29 UTC
### Description

As the title says, when dealing damage with ~~skills~~ spells, the OnHit event is not triggered. It is only activated with basic hits

### Steps to Reproduce

1) Create a weapon
2) set a common event on the "OnHit" trigger
3) use a ~~skill~~ spell

### Version with bug

0.8.0.149

### Last version that worked well

Unknow

### Affected platforms

Windows, I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2024-05-04 23:26
hmm even though you are right (verified this behavior) i can't tell if this was either intentional or not, iirc the triggers are specifically made for items / weapons, it's been never stated that they were meant for spells :thinking: @AlexVild  (??)
this makes me doubt on whether this is a bug or just some behavior that you were not personally expecting

**Comment by cydyn** [comment] 2024-05-05 09:14
@Arufonsu Spells do not activate onhit. This only works with weapons. This is the intended goal, daywalkr talked about it, that for spells you need to design a system separately

**Comment by Arufonsu** [comment] 2024-05-05 20:52
> @Arufonsu Spells do not activate onhit. This only works with weapons. This is the intended goal, daywalkr talked about it, that for spells you need to design a system separately

Thanks, after reading along other places regarding this topic, i'm closing this issue because it's basically a dupe of https://github.com/AscensionGameDev/Intersect-Engine/discussions/2202
This _is not a bug at all, but i understand the point here, if spells are used alongside weapons, they should (optionally at this point imo) carry over what the weapon is capable to do_ - follow up the topic in the original thread for now 👍🏽

**Closed by Arufonsu** 2024-05-05 20:52 UTC
Labels: bug, verified
