### ISSUE TITLE
bug: Incorrect Random NPC Movement

### ISSUE THREAD

**Issue by ValeFolken** [AscensionGameDev/Intersect-Engine#1766] opened 2023-03-14 22:36 UTC
### Description

Random Movement NPCs will always move up, instead of moving randomly.  Changing the Server Config to allow Diagonal Movement fixes this, but doesn't solve the problem for servers that wish to retain 4-directional movement.

### Steps to Reproduce

Literally just create an NPC with Random Movement.  It happens to me 100% of the time.

### Version with bug

v0.7.1.0119

### Last version that worked well

unknown

### Affected platforms

Windows

### Did you find any workaround?

Setting Diagonal Movement in Server Config fixes this, but forces the admin to run a server with 8-directional movement.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment] 2023-03-16 23:16
Unable to reproduce:

 
![imagen](https://user-images.githubusercontent.com/17498701/225773143-84d79cc1-9fd3-409f-8f47-200c486e482a.png)


https://user-images.githubusercontent.com/17498701/225773123-adfec4bd-b276-425e-99b5-a2abd0dfec06.mp4

**Comment by Richy1111** [comment] 2023-03-17 02:53
On build 0.7.1.119 I'm not seeing this bug. I tried both Editor NPC and Event NPC on both true/false of Diag.

**Comment by Arufonsu** [comment] 2023-04-16 23:50
Closing this for now, since no method to properly reproduce this has been provided yet since Mar 14, 2023.

Will reopen if the OP or anyone else who wishes to collaborate, shares over a video that shows up the reported issue.

**Closed by Arufonsu** 2023-04-16 23:50 UTC
Labels: bug, cannot be reproduced

**Comment by darkjezza** [comment] 2023-04-26 15:06
this is what happens in the newest beta build v0.7.2-beta.7 and its a fresh project 
the npcs are set to walk randomly
and when I set them to turn randomly they just stand still in the up position
then i set "EnableDiagonalMovement": true, false to true it started working
so please look into this

here is a video of what happens

https://user-images.githubusercontent.com/80877059/234615970-e7617815-7f87-4fbc-979c-7a754bcbcf40.mp4

**Comment by Arufonsu** [comment] 2023-04-26 16:10
> it worked!

Even if that _works_, there is still a problem going on with that, thanks for providing more proof and details on how to reproduce! will try to reproduce this when i can so we can verify and reopen this issue 👍🏽

**Comment by Arufonsu** [comment] 2023-04-26 16:27
Well, i hopped into a clean copy of the v0.7.2-beta.7_full build, followed what you guys have described so far in three ocasions with few variations, even tried without touching EnableDiagonalMovement at all, and so far i'm still unable to reproduce this.

https://user-images.githubusercontent.com/17498701/234640586-c90ba94b-410e-4811-a703-eba15257a6dc.mp4

**Comment by darkjezza** [comment] 2023-04-26 17:07
Ok I was wrong this is what fixes it
I'll explain in steps
First use a fresh project
Second don't touch the server config
3rd create NPC set it to randomly move
Then it should have the bug
4th open the server config change enable diagonal movement to true
Then that should fix the bug
5th then edit server config enable diagonal movement back to false
This should be working now
If I need to be clearer let me know

**Comment by Arufonsu** [comment] 2023-04-26 17:18
> Then it should have the bug

like i said, i tried to reproduce up to this as described, there's no bug at all by doing this with:
- a fresh project (tested with  0.7.1.119, 0.7.1.120 and v0.7.2-beta.7)
- never touched the server config
- created NPC that randomly moves
- there's **no bug on my side, what am i doing wrong to reproduce this?**
- the following steps you wrote make no sense, i can't even trigger the reported bug in a fresh install with default values.

**Comment by darkjezza** [comment] 2023-04-26 17:26
Ok well thanks for trying. Atlest theres a work around
