### ISSUE TITLE
bug: Consumable items, with vital experience

### ISSUE THREAD

**Issue by EspectroW94** [AscensionGameDev/Intersect-Engine#2248] opened 2024-05-11 23:22 UTC
### Description

Consumable items, with vital experience it does not give experience and when the experience bar has value, it resets it to 0.

This, in my case, happens when the character reaches level 258. I understand that this depends on the exp curve by levels in each game. but to get an idea. This is when the experience needed to level up is more or less 42,007,701,148

but to recreate this error you can do so by creating an item that gives vital experience and use it until the point where the error appears.

I suppose that the process could be accelerated by creating a very high exp curve, with that you will need few lvls.

I leave a video

https://youtu.be/rJ_6Kxx-2nc

In the video you can see that I have it configured so that at 0 + 1% you might think that "0" is the problem, but it works well at low levels. Even so, I tried using 1+1% to see if that was the solution, but the error persists.

### Steps to Reproduce

1. Create a Item Consumable Vital.
2. Set it to 0+1% or 1+1%
3. use the items until the error appears

### Version with bug

0.8.0.149

### Last version that worked well

Unknow

### Affected platforms

Windows, I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by EspectroW94** [comment] 2024-05-11 23:31
It seems that there comes a point at which exp, instead of adding, subtracts. since if the exp bar is for example at 50% and the experience item is 1%, it begins to subtract that 1% so the bar goes from 50 to 49, 48...

**Comment by Arufonsu** [comment] 2024-05-12 19:32
tried to discuss along but the user didn't like to hear the fact that this is not a bug but rather a change that should be made as enhancement, then he left the discord server, tried to explain to @EspectroW94 that we are limited here by the limits of int values:

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/7bc078b0-1160-4d41-9d99-39b2b047d9a3)

this has to be changed over to work along with long values which are capable to store values up to 9,223,372,036,854,775,807

will close this now and reopen it later on as an enhancement report + PR addressing this

**Closed by Arufonsu** 2024-05-12 19:32 UTC
Labels: bug, needs verification
