### ISSUE TITLE
System of keeping character online in combat is broken.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#543] opened 2021-02-13 22:05 UTC
**Describe the bug**
NOTE: The system works normal, I just haven't found a better title, if you want to change it to make it better for you, feel free.

The main bug here is that if you create a character, go into combat mode. Exit the game and delete the created character and log in with another character. The deleted character will still be there! If you kill the monster that is hitting him, after the combat time expires the **server will crash.**

As if that were not enough, after starting the server again, the character that killed the deleted player's monster will always remain buggy. Combat messages of logut in combat will not appear for him if you try to leave the game. If you try to select a character you go to the home screen. If you try to enter the game with the character you will receive the message "Failed to load account. Please try logging in again"

And don't stop there, that same character will have the ability to bug all the npcs that he enters in combat, if he enters combat and exits the game, the npcs will remain aggressive attacking nothing, stopped in the game (until another player attack it).

**Version Encountered**
0.7.0.106

**To Reproduce**
1. Create a character, go into combat mode
2. Exit the game and delete the created character and log in with another character
3. Kill the monster that is hitting him and wait combat time finish.

**Expected behavior**
Preferably do not crash.

**Screenshots**
https://www.ascensiongamedev.com/resources/filehost/db1e7e56fb8b05c351e6848be15f9331.mkv

**Logs**
[Intersect Server-2021_02_13-18_38_32_399.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5976576/Intersect.Server-2021_02_13-18_38_32_399.log)
[Intersect Server-2021_02_13-18_36_25_674.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5976577/Intersect.Server-2021_02_13-18_36_25_674.log)
[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5976578/errors-Intersect.Server.log)
[playerdbIntersect Server-2021_02_13-18_36_25_674.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5976579/playerdbIntersect.Server-2021_02_13-18_36_25_674.log)

**Operating System:**
Windows 10

**Additional context**
This system is a good addition to the intersect, because in pvp events, the player will not simply leave easily, among many other situations. But this system must somehow have limits.
1 - I don't really know how it should be done (I'm not a programmer and I'm not even close to being one), but there must be a condition for when the character is deleted and he is online in the game. (to avoid the above crash.)
2 - There should be a configuration on the server that would allow us to configure a time for these disconnected users, but that the characters are kept for being in combat. They shouldn't be infinitely online. Look at what I did and what the players could do.

I opened two clients, logged into two different accounts. In account 1 I left the party leader. In account 2 I created two characters in the same account and left these characters online through the combat system (two online characters from the same account is already a mistake I would say). I put them in a party and closed client 2. So thanks to this system, I can up level of several characters from the same account simultaneously because they will never disconnect unless someone shows up and make them go out of combat.

https://www.ascensiongamedev.com/resources/filehost/c90a26d61e99c366c01508616d70f65e.mkv

3 - Other situations that I did not mention above, why I did not explore further.

**Comment by jcsnider** [comment] 2021-02-13 22:14
Dupe of #434 but gonna keep this open due to the excess info.

**Comment by Arufonsu** [comment] 2021-02-13 23:37
> 
> 
> **Describe the bug**
> NOTE: The system works normal, I just haven't found a better title, if you want to change it to make it better for you, feel free.
> 
> The main bug here is that if you create a character, go into combat mode. Exit the game and delete the created character and log in with another character. The deleted character will still be there! If you kill the monster that is hitting him, after the combat time expires the **server will crash.**
> 

Quoting myself, with few changes from #434 :

-There should be a check so players are not able to log off / swap into the character selection screen during a battle for a specific period of time + a warning notice should pop up if you try to forcedly close the game client with ur character being in battle state as well:
_"If you close the game now, your character will remain online and unsupervised
for 2 minutes, do this on your own risk! [ Close anyway ]  /  [ Cancel ]"_ 

if then, the player decides to "Close anyway" his character shouldn't get disconnected right away if the client its forcedly closed, otherwise this could be easily be abused during any kind of battle that's about to be lost.


Along with this, an "already logged in" check should also be implemented. That way:
-If the user _tries to delete_ a character that's still in game/battle then the client should pop up the notice window:
_"You can't delete a character that's already logged in"_


-If the user tries _to login_ into a character while another character within the same account its still in game/battle:
_"You can't login into multiple characters, the character {0} its already logged in!"_

**Comment by dhmhc** [comment] 2021-02-14 00:52
I think it would be interesting to put a block on being able to enter another character that is in the same account, something that allows you to only enter the character you logged out of in combat, as in Tibia.

**Comment by WeylonSantana** [comment] 2021-02-14 02:08
> I think it would be interesting to put a block on being able to enter another character that is in the same account, something that allows you to only enter the character you logged out of in combat, as in Tibia.

@Arufonsu already mentioned about this possibility in his last comment, he probably mentioned all the solutions for this system to work perfectly without loopholes.

**Comment by jcsnider** [comment] 2021-02-17 21:40
Fixed the first/major part so far
![](https://www.ascensiongamedev.com/resources/filehost/344dd5505337dfc842ac856a95754ccf.png)

**Comment by jcsnider** [comment] 2021-02-17 21:55
Fixed the characters button on the escape menu not returning to character select, and I have that button disabled while in combat.
![](https://www.ascensiongamedev.com/resources/filehost/79518c226e8664ba70cae5b8f8a41d5b.png)

If you try to logout via the X button on the window, or by using the logout/desktop buttons on the escape menu you will be met with the normal prompt:
![](https://www.ascensiongamedev.com/resources/filehost/a13e190350b39d0327bbcbd39c94f44e.png)

The only remaining part is to skip character select on login, if there is a character online/being kept in the game due to combat.

**Closed** 2021-02-19 03:53 UTC
Labels: bug
